### ISSUE TITLE
[Help Wanted/Discussion] New icon for 2.0

### ISSUE THREAD

**Issue by Deadpikle** [NetSparkleUpdater/NetSparkle#100]
Hi everyone,

I'd love to have a new, high-resolution icon/graphic for NetSparkle v2.0. The current icon is rather low res and WinSparkle (a great framework for software updates for C++!) uses the same icon, so I want to remove confusion between the two frameworks and anyone else who uses the same icon.

I, uh, am a programmer and definitely not an artist. I am open to ideas and input.

Thanks for anyone who contributes!

**Comment by mphill** [comment]
![image](https://user-images.githubusercontent.com/2466039/84024682-f0760b80-a94f-11ea-9c67-4bfb5fc83c5e.png)

Just a quick idea.

**Comment by SDR0512** [comment]
![b5e6c048-e5a8-453f-90a6-5a31b93100c6_200x200](https://user-images.githubusercontent.com/58349712/86603220-58f0f080-bfc1-11ea-9468-642c8c7d4563.png)

**Comment by Mostlypyjamas** [comment]
As a suggestion, how about keeping the icon basically the same but with a large italic # symbol in the bottom right hand corner of the icon - as in a gentle nudge towards C# use - we are actually a VB.net shop, but seeing a #  on something always suggests .NET to me :)

**Comment by Deadpikle** [comment]
> 
> 
> As a suggestion, how about keeping the icon basically the same but with a large italic # symbol in the bottom right hand corner of the icon - as in a gentle nudge towards C# use - we are actually a VB.net shop, but seeing a # on something always suggests .NET to me :)

I like this idea. Perhaps this in combination with a slight color change would work well.

I see in the WinSparkle repo that the icon apparently comes from the old Tango Project icon set (as seen here)[https://github.com/vslavik/winsparkle/tree/master/artwork]).

**Comment by Deadpikle** [comment]
Here's the .zip of the SVG (public domain) for the current icon. If anyone knows someone who knows how to use Inkscape or mess with vectors...😅 otherwise I'll tackle it...someday...probably after docs are updated...

[software-update-available.zip](https://github.com/NetSparkleUpdater/NetSparkle/files/5179984/software-update-available.zip)

**Comment by Deadpikle** [comment]
![software-update-available](https://user-images.githubusercontent.com/5092399/104628511-52c18800-5666-11eb-981b-2cc0181df8d2.png)

If at first you don't have a graphic designer, do it yourself. 😅 Sharp/pound symbol SVG from https://www.svgrepo.com/svg/42960/hashtag, which is a CC0 license.

Maybe someday someone with actual graphic design skills will come along and help us out. Until then, here goes nothing!

**Comment by Mostlypyjamas** [comment]
I really like that - exactly encapsulates the point of the package i think
