### ISSUE TITLE
AppCastGenerator - cannot generate keys

### ISSUE THREAD

**Issue by miroelk** [NetSparkleUpdater/NetSparkle#104]
Hi,
I'm using latest preview as of writing this and I'm not able to generate keys.

I have tried adding Nuget to my project (using .NET Core 3.1), but I got an error:
```
Package 'NetSparkleUpdater.Tools 2.0.0-preview20200614001' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
```
The Nuget is not yet compatible with .NET Core 3.1, no problem, so I cloned the repo (develop branch) and built project NetSparkle.Tools.AppCastGenerator and it was built sucessfully.
Afterwards I opened cmd and ran command **generate_appcast.exe --generate-keys** and got error:
```
Cannot use stream for resource [C:\Repos\NetSparkle\src\NetSparkle.Tools.AppCastGenerator\obj\Release\netcoreapp3.0\generate_appcast.deps.json]: No such file or directory
A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\Program Files\dotnet'.
Failed to run as a self-contained app.
  - The application was run as a self-contained app because 'C:\Repos\NetSparkle\src\NetSparkle.Tools.AppCastGenerator\obj\Release\netcoreapp3.0\generate_appcast.runtimeconfig.json' was not found.
  - If this should be a framework-dependent app, add the 'C:\Repos\NetSparkle\src\NetSparkle.Tools.AppCastGenerator\obj\Release\netcoreapp3.0\generate_appcast.runtimeconfig.json' file and specify the appropriate framework.
```
Could you please advise, how should this be properly used? Maybe I'm just using it wrong...

**Comment by Deadpikle** [comment]
Hmmm, it seems like there are two problems:

1. Adding the tools via NuGet should work -- the tools both target `netcoreapp3.0`, but clearly something thought it was for .NET Framework. Hm.
2. The tools aren't distributed as self-contained apps (they probably should be).

Could you try installing the .NET Core Runtime (https://dotnet.microsoft.com/download/dotnet-core/3.1 -- see the `Desktop Runtime 3.1.5` section) and seeing if that helps, here?

**Comment by miroelk** [comment]
After I reinstalled Desktop Runtime, it started working.

The interesting point here is that even though I had already installed .NET Core SDK and when I listed runtimes, Desktop Runtime was there. But it wasn't installed correctly, probably because of the missing dll, but after reinstalling it, just the Desktop Runtime, it was fixed and is working now.

**Comment by Deadpikle** [comment]
Thanks again for this report. I've done a few things here:

1. Updated the readme in this repo to make it more obvious that you need the desktop runtime installed
2. Added a readme.txt to the tools NuGet to tell people to use the desktop runtime
3. Don't publish tools trimmed (in case this was the real cause...)
4. Updated tools to use .NET Core 3.1

I ran a test, and from a new .NET Core 3.1 project, I could successfully reference the NetSparkle tools preview with no issues.

Thanks!
