### ISSUE TITLE
AppCastGenerator - Incorrect URL generated 

### ISSUE THREAD

**Issue by bragma** [NetSparkleUpdater/NetSparkle#106]
Hi,
I've noticed an error in the file generated by AppCastGenerator. The enclosure url contains a ) character at the end, I think the cause is [here](https://github.com/NetSparkleUpdater/NetSparkle/blob/9a5afbc8f523d0d3a5c67ad401f8ee3573c89b00/src/NetSparkle.Tools.AppCastGenerator/Program.cs#L231):

Notice the ) at the end:

`var remoteUpdateFile = $"{opts.BaseUrl}/{(opts.PrefixVersion ? $"{version}/" :"")}{HttpUtility.UrlEncode(fileInfo.Name)})";`

Fixed line should be:

`var remoteUpdateFile = $"{opts.BaseUrl}/{(opts.PrefixVersion ? $"{version}/" :"")}{HttpUtility.UrlEncode(fileInfo.Name)}";`

I'm working on a PR.

**Comment by bragma** [comment]
Sure let me 10 mins to work on it!

**Comment by bragma** [comment]
Ok it actually took 1 minute :)
I was looking for tests to the generator program itself but there are none. Still, it will take more time to work on that.

**Comment by Deadpikle** [comment]
No worries on the tests. I realize they are very much non-existant and very much need to be created, but this will do for now. Thanks again -- will take a look over lunch today.

**Comment by Deadpikle** [comment]
Thank you again! This will be in `2.0.0-preview20200618001` whenever CI/CD finishes running.
