### ISSUE TITLE
Interface for logging instead of inheriting from LogWriter

### ISSUE THREAD

**Issue by bragma** [NetSparkleUpdater/NetSparkle#108]
Hi,
I am using NLog in my WPF application. LogWriter has a virtual PrintMessage method which is ok, I created a class and redefined it to use NLog's methods, still PrintDiagnosticToConsole does not fit well in this scenario. NLog and other loggers have more complex methods to define log sinks and have way more options than just Console/Debug.

It would be much better to log using an interface instead. This would allow me to write a minimal class implementing PrintMessage without inheriting from LogWriter and have existing LogWriter class as implementation.

What do you think?

**Comment by Deadpikle** [comment]
Great suggestion. It makes a lot of sense to do this.

`2.0.0-preview20200621001` uses an `ILogger` interface rather than `LogWriter`. Unfortunately, this caused a change to `IAppCastHandler`, too, but since we are still pre-release-candidate, this breaking change was OK. 😅 

Thank you!
