### ISSUE TITLE
Unhandled exception if DSA signature is invalid

### ISSUE THREAD

**Issue by anti-matter** [NetSparkleUpdater/NetSparkle#119]
When a file is downloaded and if the DSA signature check fails, NetSparkle causes an unhandled exception.

The offending code is on line 1015 in SparkleUpdater.cs

`DownloadHadError?.Invoke(_itemBeingDownloaded, _downloadTempFileName, new NetSparkleException(e.Error.Message));`

I believe the correction should be to use the errorMessage that is generated instead of expecting one (that doesn't exist) from the event arguments. e.Error is null so the exception occurs trying to grab the Message.

`DownloadHadError?.Invoke(_itemBeingDownloaded, _downloadTempFileName, new NetSparkleException(errorMessage));`

**Comment by Deadpikle** [comment]
This is fixed in 2.0.0-preview20200726001. Thanks so much for doing the digging for me and showing exactly what needed to be fied!

**Comment by anti-matter** [comment]
Thanks for the quick turn-around!
