### ISSUE TITLE
I made a package generator with gui

### ISSUE THREAD

**Issue by brutalzinn** [NetSparkleUpdater/NetSparkle#121]
https://github.com/brutalzinn/NetSparkle-Generator-Package

thanks for the library.

**Comment by Deadpikle** [comment]
Hi @brutalzinn! Apologies for the slow reply. Thank you for making a package generator GUI; however, it appears that your repo is down or otherwise closed, so I will be closing this issue. Thanks for your participation in the NetSparkleUpdater repo!
