### ISSUE TITLE
[Question] When will the new release version be released?

### ISSUE THREAD

**Issue by nk915** [NetSparkleUpdater/NetSparkle#125]
Hi. Can't find info - 
When will the new release version be released?

**Comment by Deadpikle** [comment]
Hi @nk915,

The answer is "when it's ready." :) Generally speaking, #61 has the details on what is left. The preview versions are fairly stable at this point, but they lack some documentation still. I also need to get a new icon out.

I'm very busy right now, this project is entirely done in my free time, and I receive no money for this, so it's done when it is done. Contributions are welcome!

**Comment by Deadpikle** [comment]
@nk915,

The answer is TODAY, 20 April, 2021! 🥳 🥳 🥳 🥳 🥳 🥳
