### ISSUE TITLE
New app version is not considered

### ISSUE THREAD

**Issue by anti-matter** [NetSparkleUpdater/NetSparkle#126]
Can someone please tell why the new version with a much higher version number is not seen as a new one?

`2020/10/07 17:51:34.189|DEBUG|Application updater: Found an item in the app cast: version 1.2.2030.0 () -- os = windows 
2020/10/07 17:51:34.189|DEBUG|Application updater: While parsing app cast item, converted 'Wed, 07 Oct 2020 18:14:53 GMT' to 10/7/2020 11:14:53 AM.
2020/10/07 17:51:34.189|DEBUG|Application updater: Found an item in the app cast: version 1.2.2021.0 () -- os = windows 
2020/10/07 17:51:34.189|DEBUG|Application updater: App cast successfully downloaded and parsed. Getting available updates... 
2020/10/07 17:51:34.189|DEBUG|Application updater: Touch the last check timestamp
2020/10/07 17:51:34.189|DEBUG|Application updater: Installed version is valid, no update needed (1.2.2021.0)
`

**Comment by Deadpikle** [comment]
Hi @anti-matter,

Please post your app cast here (anonymized as necessary) so I can take a look. Thanks!

(Did you click "Skip this Version" previously?)

**Comment by anti-matter** [comment]
No, I did not say skip any version.

`<rss xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle" xmlns:dc="http://purl.org/dc/elements/1.1/" version="2.0">
<channel>
<title>REDACTED</title>
<link>/v0.1/public/sparkle/apps/REDACTED</link>
<item>
<title>Version (1.2.2030.0)</title>
<description><div style='font-size: 110%; font-family: Helvetica, Arial, sans-serif;'><p>Initial desktop production release.</p> <p><strong>Notable improvements in this release:</strong></p> <ul> <li>None</li> </ul> </div></description>
<pubDate>Thu, 08 Oct 2020 00:39:03 GMT</pubDate>
<enclosure sparkle:version="1.2.2030.0" sparkle:shortVersionString="" url="https://appcenter-filemanagement-distrib1ede6f06e.azureedge.net/5bcbbaf0-5c5b-4f47-88f4-8a7f0a73e401/REDACTED.msi?sv=2019-02-02&sr=c&sig=%2BkhoQUU7mf2YBw49OMrZ5%2BM9EERcOPXiehfQ%2BFmrp2c%3D&se=2020-10-09T00%3A50%3A32Z&sp=r" length="79888384" type="application/octet-stream"/>
<sparkle:minimumSystemVersion/>
</item>
<item>
<title>Version (1.2.2021.0)</title>
<description><div style='font-size: 110%; font-family: Helvetica, Arial, sans-serif;'><p>Initial desktop production release.</p> <p><strong>Notable improvements in this release:</strong></p> <ul> <li>None</li> </ul> </div></description>
<pubDate>Wed, 07 Oct 2020 18:14:53 GMT</pubDate>
<enclosure sparkle:version="1.2.2021.0" sparkle:shortVersionString="" url="https://appcenter-filemanagement-distrib2ede6f06e.azureedge.net/c3816af5-4622-4d0d-94b9-73248b813d7e/REDACTED.msi?sv=2019-02-02&sr=c&sig=S7rmivPI1p4EanYPWcO8hAfFatesOlfIOsa4fhGQ83Q%3D&se=2020-10-09T00%3A48%3A02Z&sp=r" length="79888384" type="application/octet-stream"/>
<sparkle:minimumSystemVersion/>
</item>
</channel>
</rss>`

**Comment by Deadpikle** [comment]
Thanks. I'll have to take a look. I'll try to do so soon.

**Comment by anti-matter** [comment]
Ugh. Never mind. Error on our part. The dsa signature setting, which was working, suddenly stopped. Just need to figure out why its not being set in our build process. Sorry.

**Comment by Deadpikle** [comment]
Ah, glad you figured it out!

All the same, I went ahead and added some additional debug `LogWriter` statements to help people debug these things in the future: see commit dfcccd288cb25c1159cad0c7be83f287f931d3c1 and preview version `2.0.0-preview20201008001`. The log now states why it is rejecting an app cast item as being a valid update. Hopefully that will help catch such issues sooner.

Thanks!
