### ISSUE TITLE
Bug: Windows MSI, RelaunchAfterUpdate wants to start dll instead of exe

### ISSUE THREAD

**Issue by KevinBassaDevelopment** [NetSparkleUpdater/NetSparkle#146]
When using RelaunchAfterUpdate = true with an MSI installer, the dll gets called instead of the exe.

As a workaround this can be fixed by overwriting SparkleUpdater.cs:
```
 protected virtual async Task RunDownloadedInstaller(string downloadFilePath){
    ...

    // string cmdLine = Environment.CommandLine;  // this results in path to dll
    string cmdLine = Configuration.ApplicationName + ".exe";  // dirty workaround: assume that ApplicationName  equals assemblyName and build exePath. What should be done: assemblyName could be included in config.

    ...
}
```

**Comment by Deadpikle** [comment]
Hi @KevinBassaDevelopment,

Thanks for your report!

Does this happen with WinForms or WPF? On .NET Core or .NET Framework? (Or does that matter?)

Thanks!

**Comment by Deadpikle** [comment]
For context, here's the lines we're talking about:

https://github.com/NetSparkleUpdater/NetSparkle/blob/40e9454fdc59b217313eca1a66f58661f81039e9/src/NetSparkle/SparkleUpdater.cs#L1212-L1263

Boy, though, there's a lot of solutions to this problem, and I'm not sure which to use right now or sure if there's a universal solution: https://stackoverflow.com/questions/616584/how-do-i-get-the-name-of-the-current-executable-in-c

I'm not sure that the type of installer has anything to do with it...? Would need to test.

**Comment by KevinBassaDevelopment** [comment]
I use wpf dotnetcore!

**Comment by KevinBassaDevelopment** [comment]
> For context, here's the lines we're talking about:
> 
> https://github.com/NetSparkleUpdater/NetSparkle/blob/40e9454fdc59b217313eca1a66f58661f81039e9/src/NetSparkle/SparkleUpdater.cs#L1212-L1263
> 
> Boy, though, there's a lot of solutions to this problem, and I'm not sure which to use right now or sure if there's a universal solution: https://stackoverflow.com/questions/616584/how-do-i-get-the-name-of-the-current-executable-in-c
> 
> I'm not sure that the type of installer has anything to do with it...? Would need to test.


I think it would be great to let the user pass in the name of the executable + the app name.

Currently both are generated from within the updater, but as a user I might use different solutions which differ from 1 universal solution.

**Comment by Deadpikle** [comment]
@KevinBassaDevelopment Sorry for the long wait here.

`2.0.0-preview20210111001` now includes two new options to make this easier to configure:

* `RestartExecutablePath` to set the working directory
* `RestartExecutableName` to set the name of the executable (aka override the `Environment.CommandLine` call)

Hope that helps! :)

**Comment by KevinBassaDevelopment** [comment]
Very nice, will try it tomorrow, thanks :)!

**Comment by idan-h** [comment]
You can solve it by using this instead: System.Diagnostics.Process.GetCurrentProcess().MainModule.FileName

I checked it on .net core 3 and it works well
