### ISSUE TITLE
Question about usage

### ISSUE THREAD

**Issue by idan-h** [NetSparkleUpdater/NetSparkle#158]
Hi, I'm sorry if my question is dumb, but I did not understand some things:

How do I sign the inno setup file?

Anonther question is, I want to run my setup with args. Can I do that somehow?

Thank you very much for all the effort!

**Comment by Deadpikle** [comment]
Hi @idan-h! Don't worry about it -- often if one person asks a question, more people than just that one person have the same question!

> How do I sign the inno setup file?

If you're using Inno Setup for your installer, you can find some documentation on signing the installer [here in Inno Setup's docs](https://jrsoftware.org/ishelp/index.php?topic=setup_signtool). You'll also need a code signing certificate. Both NetSparkleUpdater and Inno Setup are not in charge of how you actually sign your certificates. I did a quick web search, and it looks like there is a [very helpful StackOverflow post here on the subject](https://stackoverflow.com/questions/252226/signing-a-windows-exe-file). For "real" code signing, you'll have to purchase a certificate somewhere.

> Anonther question is, I want to run my setup with args. Can I do that somehow?

Yes! You can run your installer with extra arguments by setting the `CustomInstallerArguments` property on the `SparkleUpdater` object. You can see how that works here: https://github.com/NetSparkleUpdater/NetSparkle/blob/107e8fcd3d5954da1bea9d6dd8d44a113f3e1cbc/src/NetSparkle/SparkleUpdater.cs#L1281-L1285

> Thank you very much for all the effort!

You're welcome.

**Comment by idan-h** [comment]
Thanks for the quick response
