### ISSUE TITLE
Might be a bug when calling CheckForUpdatesQuietly()

### ISSUE THREAD

**Issue by idan-h** [NetSparkleUpdater/NetSparkle#159]
On File SparkleUpdater.cs Line 1564:
if (UpdateDetected != null)
{
    UpdateDetected(this, ev);
    // if the client wants the default UI then show them
    switch (ev.NextAction)
    {
        case NextUpdateAction.ShowStandardUserInterface:
            LogWriter.PrintMessage("Showing standard update UI");
            OnWorkerProgressChanged(_taskWorker, new ProgressChangedEventArgs(1, updates));
            break;
    }
}

If there is no UpdateDetected Event it never downloads the update, even if an update was found.
I dont know if this is intended, but letting the switch out of the 'if (UpdateDetected != null)' might solve it..

**Comment by Deadpikle** [comment]
Hi again. This is working as intended. `CheckForUpdatesQuietly` is supposed to check for events _quietly_ -- in other words, nothing will be shown unless it is handled by the program that called `CheckForUpdatesQuietly` in the first place. `CheckForUpdatesQuietly` just checks to see if there _is_ an update -- no more, no less. Please see the `HandleEventsYourself` sample (`_updateInfo = await _sparkle.CheckForUpdatesQuietly();` -> handle update) --- this sample shows how to handle all the downloading and such in code by handling events yourself.

If you want something to be handled and/or shown to the user without having to do more work yourself, use `CheckForUpdatesAtUserRequest()` or trigger the updater with `StartLoop(true, true)` like the other UI samples.

**Comment by Deadpikle** [comment]
I will review the docs here, though, as upon further review, the documentation here is a little confusing, as it says a UI should be shown.

Thanks.

**Comment by idan-h** [comment]
It is alright, glad it helped with something
