### ISSUE TITLE
Add documentation on technically only needing latest version in app cast

### ISSUE THREAD

**Issue by Deadpikle** [NetSparkleUpdater/NetSparkle#168]
Technically, only the latest item is needed. Docs on this would help clarify to end users that CI/CD might be easier than they think since they don't "need" the full history.

**Comment by johncclayton** [comment]
done as part of the PR here https://github.com/NetSparkleUpdater/NetSparkle/pull/171

**Comment by Deadpikle** [comment]
Merged in README changes on 2021-04-18.
