### ISSUE TITLE
UpdateAvailableResult.None not working?

### ISSUE THREAD

**Issue by Kyberal** [NetSparkleUpdater/NetSparkle#169]
Using UIFactory for WinForms.
I want to know when the user closes the "Update Available" window.
I have subscribed to the "UserRespondedToUpdate" event.
The "UpdateAvailableResult.None" event result doesn't works.

```
private void _sparkleUpdateDetector_UserRespondedToUpdate(object sender, NetSparkleUpdater.Events.UpdateResponseEventArgs e)
{
    if (e.Result == UpdateAvailableResult.RemindMeLater)
    {
        Console.WriteLine("UpdateAvailableResult.RemindMeLater");
    }
    if (e.Result == UpdateAvailableResult.None)
    {
        // Not working
        Console.WriteLine("UpdateAvailableResult.None");
    }
}
```

Is this a bug or am I doing it wrong?
Or is there even a way to detect when a "SparkleUpdater" has all it's windows closed?

Thanks!

**Comment by Deadpikle** [comment]
@Kyberal Hi! Welcome!

Thanks for reporting this. I believe you've found a bug. 😅 The `.None` case is not being handled when the user update window is closed.

https://github.com/NetSparkleUpdater/NetSparkle/blob/d9e2297c0a6eff12b0a30d0aecc6b699f6ac2267/src/NetSparkle/SparkleUpdater.cs#L1662-L1688

**Comment by Deadpikle** [comment]
Had to fix this in multiple UI packages and in the core library. The WinForms UI frontend was working already.

* [x] Core
* [x] WPF
* [x] Avalonia

The bug fix has been pushed out in the following NuGet package: `2.0.0-preview20210314001`
