### ISSUE TITLE
cyrillic support in bat file

### ISSUE THREAD

**Issue by devlabpro** [NetSparkleUpdater/NetSparkle#175]
Hello
bat file that is generated to run the installer does not start the installer if the path to the installer file contains Cyrillic characters. I managed to fix this by adding `chcp 65001> nul` to the bat file. I would like to see this fix as part of the nuget package.

**Comment by devlabpro** [comment]
if necessary, I can create a PR from the fork

**Comment by Deadpikle** [comment]
Please open a PR! That will help me get to it sooner. Thank you! :)

Would this also fix #112? Any idea?

**Comment by devlabpro** [comment]
create PR https://github.com/NetSparkleUpdater/NetSparkle/pull/176

> Would this also fix #112? Any idea?

yes, should help to fix it

**Comment by Deadpikle** [comment]
I merged in your PR. Thank you very much for your PR! I greatly appreciate it.
