### ISSUE TITLE
IIS Web Server will not serve up a file with an extension of .signature!

### ISSUE THREAD

**Issue by SeanAWalsh** [NetSparkleUpdater/NetSparkle#188]
Took me a while, this one.

I've had NetSparkle working in UnSafe mode but never got my head around the whole public/private key thing - at least I thought I hadn't! So I never got 

	_sparkle = new SparkleUpdater("http://.../appcast.xml", new Ed25519Checker(SecurityMode.Strict, "Public Key")

working.

So, today, dusted off my Visual Studio, tapped into your lovely LogWriter and lo and behold, on the console window saw that the attempt to download "http://.../appcast.xml.signature" was reporting a "404 Not Found" error even though the file was there! Changing the file name to "appcast.xml.signature.txt" or "appcast.xml.txt" worked fine. Just ".signature" is persona-non-grata on my server and will report a "404 Not Found" error.

Nice one.

The server is running Windows IIS Server (v 8.5.9600.16484) - not the oldest and not the newest. So I reckon there's a setting somewhere that can be tweaked in IIS to change this but working on the assumption that not everyone has control of their server...

I did this:

- src/NetSparkle.Tools.AppCastGenerator/Program.cs

		...
		public string PathToKeyFiles { get; set; }

		[Option("signature-file-extension", SetName = "local", Required = false, 
			HelpText = "Suffix (without '.') to append to appcast.xml for signature file", 
			Default = "signature")]
		public string SignatureFileExtension { get; set; }

		#region Key Generation

		[Option("generate-keys", SetName = "keys", Required = false, HelpText = "Generate keys", Default = false)]
		...

		...
		if (_signatureManager.KeysExist())
		{
			var appcastFile = new FileInfo(appcastFileName);
			var signatureFile = $"{appcastFileName}.{opts.SignatureFileExtension}";
			...

- src/NetSparkle/AppCastHandlers/XMLAppCast.cs

		public class XMLAppCast : IAppCastHandler
		{
			private Configuration _config;
			private string _castUrl;
			
			// New private field
			//
			private string _signatureFileExtension;
			
			/// (provided by <see cref="SparkleUpdater"/> via the 
			/// <see cref="SparkleUpdater.AppCastDataDownloader"/> property.</param>
			/// <param name="castUrl">full URL to the app cast file</param>
			/// <param name="signatureFileExtension">Suffix file extension for signature files (e.g. "signature")</param>
			...
			public void SetupAppCastHandler(IAppCastDataDownloader dataDownloader, string castUrl, 
				string signatureFileExtension, Configuration config, ISignatureVerifier signatureVerifier,
				ILogger logWriter = null)
			{
				_dataDownloader = dataDownloader;
				_config = config;
				_castUrl = castUrl;
				
				// signatureFileExtension arg stored in private field
				//
				_signatureFileExtension = signatureFileExtension;
				...
			
			public bool DownloadAndParse()
			{
				...
				try
				{
					// Remove hard-wired ".signature"
					//
					signature = _dataDownloader.DownloadAndGetAppCastData($"{_castUrl}.{_signatureFileExtension}");
				}
				...

- src\NetSparkle\Interfaces\IAppCastHandler.cs

		// Allow for passing of SignatureFileExtension to IAppCastHandler.SetupAppCastHandler
		//
		
		/// <param name="signatureFileExtension">Suffix file extension for signature files (e.g. "signature")</param>
		void SetupAppCastHandler(IAppCastDataDownloader dataDownloader, string castUrl, string signatureFileExtension, 
			Configuration config, ISignatureVerifier signatureVerifier, ILogger logWriter = null);

- src\NetSparkle\SparkleUpdater.cs

		public SparkleUpdater(string appcastUrl, ISignatureVerifier signatureVerifier, string referenceAssembly,
			IUIFactory factory)
		{
			...
			SignatureVerifier = signatureVerifier;
			
			// Default to ".signature" (non-breaking change)
			//
			SignatureFileExtension = "signature";
			...
			
			...
			public string AppCastUrl { get; set; }

			/// <summary>
			/// Suffix file extension for signature files (e.g. "signature")
			/// </summary>
			public string SignatureFileExtension { get; set; }

			...
			
			...
			protected async Task<UpdateInfo> GetUpdateStatus(Configuration config, bool ignoreSkippedVersions = false)
			{
				...
				if (AppCastHandler == null)
				{
					AppCastHandler = new XMLAppCast();
				}
				
				// Pass extension to SetupAppCastHandler
				//
				AppCastHandler.SetupAppCastHandler(AppCastDataDownloader, AppCastUrl, SignatureFileExtension, 
							config, SignatureVerifier, LogWriter);
			
All of which means I can do this...

	_sparkle = new SparkleUpdater("http://.../appcast.xml", new Ed25519Checker(SecurityMode.Strict, "Public Key"))
	{
		UIFactory = new NetSparkleUpdater.UI.WinForms.UIFactory(Icon)
		{
		    AdditionalReleaseNotesHeaderHTML = "<style> body { font-family: Arial, Helvetica, sans-serif; } </style>"
		},
		ShowsUIOnMainThread = true,
		RelaunchAfterUpdate = true,
		SignatureFileExtension = "signature.txt"
	};

	_sparkle.StartLoop(true, true);

which uses "http://.../appcast.xml.signature.txt" and all is right in my world...

**Comment by WaseemAlkurdi** [comment]
I ran into this before - you'll have to whitelist the `.signature` extension in IIS.
You might want to refer to this Microsoft article: https://docs.microsoft.com/en-us/iis/configuration/system.webserver/security/requestfiltering/fileextensions/

**Comment by SeanAWalsh** [comment]
Thanks for this. I realised I could do this but presumably others can't and would need to contact a web hosting company and prevail upon them to do it. That's why I suggested a method whereby we give the NetSparkle user the ability to sidestep the issue.

**Comment by Deadpikle** [comment]
Yeah, this would better be handled on IIS itself, but given that some users won't be able to do that, we should make this more configurable for them.

**Comment by Deadpikle** [comment]
This is now done; however, I did make one change to your suggestions:

Rather than giving `SparkleUpdater` the signature extension, I added that to `XMLAppCast`. I think it made more sense there. I'm debating adding it to the interface buuuuuut don't think it's necessary.

```csharp
_sparkle = new SparkleUpdater("https://netsparkleupdater.github.io/NetSparkle/files/sample-app/appcast.xml", new DSAChecker(Enums.SecurityMode.Strict))
{
    UIFactory = new NetSparkleUpdater.UI.WPF.UIFactory(NetSparkleUpdater.UI.WPF.IconUtilities.ToImageSource(icon)),
    AppCastHandler = new AppCastHandlers.XMLAppCast() { SignatureFileExtension = "txt"}
};
```

or

```csharp
_sparkle = new SparkleUpdater("https://netsparkleupdater.github.io/NetSparkle/files/sample-app/appcast.xml", new DSAChecker(Enums.SecurityMode.Strict))
{
    UIFactory = new NetSparkleUpdater.UI.WPF.UIFactory(NetSparkleUpdater.UI.WPF.IconUtilities.ToImageSource(icon))
};
if (_sparkle.AppCastHandler is AppCastHandlers.XMLAppCast xmlAppCast)
{
    xmlAppCast.SignatureFileExtension = "txt";
}
```

**Comment by SeanAWalsh** [comment]
Nice Job.

Thanks again.

I had to say:

    using NetSparkleUpdater.AppCastHandlers;
    ...
    AppCastHandler = new XMLAppCast() { SignatureFileExtension = "txt"}

or

    AppCastHandler = new NetSparkleUpdater.AppCastHandlers.XMLAppCast() { SignatureFileExtension = "txt"}

The line as written wouldn't compile for me.
But all good. And really nice work as always.

**Comment by SeanAWalsh** [comment]
Agree with your thoughts regarding the placement of the property. Spot on, as usual.
