### ISSUE TITLE
The 2.0 launch is imminent.

### ISSUE THREAD

**Issue by Deadpikle** [NetSparkleUpdater/NetSparkle#189]
Speak now or forever hold your peace on breaking changes. I think (I HOPE) I'm done with breaking changes.

All I want to do now is roll out an official 2.0 version, update change logs and the releases page, etc. I have no more code changes planned unless someone sends one in on a PR or there is a bug to fix that I can reliably replicate.

Hopefully 2.0 will be out within a week.

**Comment by SeanAWalsh** [comment]
Minor: README.MD
"#### DAS vs Ed25519 Signatures"  should read "#### DSA vs Ed25519 Signatures"

**Comment by Deadpikle** [comment]
Thanks for that -- fixed that typo.

2.0 is now out! 🥳

**Comment by SeanAWalsh** [comment]
Excellent! Well done.
