### ISSUE TITLE
App cast generator: HttpUtility.UrlEncode seems to change ' ' to '+' rather than '%20'

### ISSUE THREAD

**Issue by Deadpikle** [NetSparkleUpdater/NetSparkle#195]
This causes problems when uploading files. Need to look into this.

**Comment by evgeny-bykov** [comment]
Hi,
We could replace `HttpUtility.UrlEncode` with `Uri.EscapeDataString` and it would fix the issue.
What do you think?

**Comment by Deadpikle** [comment]
Based on a quick online search, that'd probably work.

I'm swamped right now. Will get to testing it out when I can. Thank you for your input; I appreciate it greatly! :)
