### ISSUE TITLE
Recent changes to -e option for AppCastGenerator mean it is now mandatory (documentation still says defaults to exe)

### ISSUE THREAD

**Issue by SeanAWalsh** [NetSparkleUpdater/NetSparkle#201]
How does one pass an IEnumerable option in on the command line anyway?

**Comment by SeanAWalsh** [comment]
4>NetSparkleUpdaterAppCastGenerator 2.0.8
4>Copyright c ndreisg 2019, Deadpikle 2020-2021
4>
4>ERROR(S):
4>  Error setting value to option 'e, ext': Check if Option or Value attribute
4>  values are set properly for the given type.

when "-e exe" is not supplied

I suspect what is needed is set option back to string type and split:

    [Option('e', "ext", SetName = "local", Required = false, HelpText = "Search for file extensions.", Default = "exe")]
    public string Extension { get; set; }

    ...

    var searches = opts.Extension.Split(',').ToList().Select(extension => $"*.{extension}");

to allow

    ... -e exe,msi

to yield "\*.exe" and "\*.msi" which is what it looks like is intended

**Comment by Deadpikle** [comment]
Yes, this'll need to be fixed ASAP since this seems to break the app cast generator. I will try to get to this ASAP, but I'm really busy today (and probably for the next few days).

Thank you for reporting.
