### ISSUE TITLE
WinForms and NetCore DownloadProgressWindow Labels Overlap Icon

### ISSUE THREAD

**Issue by SeanAWalsh** [NetSparkleUpdater/NetSparkle#212]
1. The "Downloading APP" and "0 MB / 10 MB" labels are too far to the left and partially obscure the icon
2. For me the Window is not wide enough to display my product name and version number (I widened to 466 pixels)
3. The imgAppIcon SizeMode is set to AutoSize. This obliges one to guess its size and try to make an icon just big enough to fit.
This property (and, in my opinion the same for all icons and images) should be Zoom (I'll raise a separate issue for this)

I think this might influence issue #123 for folks with certain screen settings if they are using a larger icon file and expecting it to be resized to fit the box and that's why buttons disappear off the bottom of the form. I'm off to test this hypothesis

**Comment by Deadpikle** [comment]
I have reworked the UIs for the download progress windows in WinForms (both for .NET Core and .NET Framework) to use a `TableLayoutPanel`, which should help alleviate the issues that you are seeing as well as fix text wrapping for the labels. The icon zooming is fixed per the other issue.
