### ISSUE TITLE
Image and Icon SizeModes are AutoSize - Should Be Zoom

### ISSUE THREAD

**Issue by SeanAWalsh** [NetSparkleUpdater/NetSparkle#213]
I believe that

    NetSparkle.UI.WinForms.NetCore\CheckingForUpdatesWindow.Designer.cs
    NetSparkle.UI.WinForms.NetCore\MessageNotificationWindow.Designer.cs
    NetSparkle.UI.WinForms.NetFramework\CheckingForUpdatesWindow.Designer.cs
    NetSparkle.UI.WinForms.NetFramework\MessageNotificationWindow.Designer.cs

    NetSparkle.UI.WinForms.NetCore\DownloadProgressWindow.resx
    NetSparkle.UI.WinForms.NetCore\UpdateAvailableWindow.resx
    NetSparkle.UI.WinForms.NetFramework\DownloadProgressWindow.resx

Use AutoSize where (I think) Zoom is intended

See: https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.pictureboxsizemode?view=net-5.0

says
* AutoSize - The PictureBox is sized equal to the size of the image that it contains.
* CenterImage	- The image is displayed in the center if the PictureBox is larger than the image. If the image is larger than the PictureBox, the picture is placed  in the center of the PictureBox and the outside edges are clipped.
* Normal - The image is placed in the upper-left corner of the PictureBox. The image is clipped if it is larger than the PictureBox it is contained in.
* StretchImage - The image within the PictureBox is stretched or shrunk to fit the size of the PictureBox.
* Zoom - The size of the image is increased or decreased maintaining the size ratio.

I note that

     NetSparkle.UI.WinForms.NetCore\ToastNotifier.designer.cs
     NetSparkle.UI.WinForms.NetFramework\ToastNotifier.designer.cs

use a SizeMode of CenterImage and the Form Constructor goes to the trouble of creating a 48 x 48 version of the icon.
The others don't and so strange things happen with larger images. As I said in Issue #212, I think this may be part of issue #123's problems. I have a user with this problem (his buttons are not visible on the Form at all). I'll see if I can fix him.

**Comment by Deadpikle** [comment]
Fixed in 2b169dc542cfae0c34fab6091ee4db26f561fa3f and ddb336f227bc02c3837da70a062113c6b341315d

**Comment by Deadpikle** [comment]
Thanks for your notes on that!
