### ISSUE TITLE
CheckForUpdatesAtUserRequest doesn't close checking for updates dialog (InvalidOperationException)

### ISSUE THREAD

**Issue by brads55** [NetSparkleUpdater/NetSparkle#221]
Hi,

When calling the CheckForUpdatesAtUserRequest function using the .NET Core winforms UI, the checking for updates dialog does not get closed. I believe there is an issue in the following code from `SparkleUpdater.cs` regarding task scheduling.

```c#
        public async Task<UpdateInfo> CheckForUpdatesAtUserRequest(bool ignoreSkippedVersions = false)
        {
            CheckingForUpdatesWindow = UIFactory?.ShowCheckingForUpdates(this);
            if (CheckingForUpdatesWindow != null)
            {
                CheckingForUpdatesWindow.UpdatesUIClosing += CheckingForUpdatesWindow_Closing; // to detect canceling
                CheckingForUpdatesWindow.Show();
            }
            // artificial delay -- if internet is super fast and the update check is super fast, the flash (fast show/hide) of the
            // 'Checking for Updates...' window is very disorienting, so we add an artificial delay
            await Task.Delay(250);
            UpdateInfo updateData = await CheckForUpdates(true, ignoreSkippedVersions); // handles UpdateStatus.UpdateAvailable (in terms of UI)
            if (CheckingForUpdatesWindow != null) // if null, user closed 'Checking for Updates...' window or the UIFactory was null
            {
                CheckingForUpdatesWindow?.Close();
                CallFuncConsideringUIThreads(() =>
                {
                    switch (updateData.Status)
                    {
                        case UpdateStatus.UpdateNotAvailable:
                            UIFactory?.ShowVersionIsUpToDate(this);
                            break;
                        case UpdateStatus.UserSkipped:
                            UIFactory?.ShowVersionIsSkippedByUserRequest(this); // they can get skipped version from Configuration
                            break;
                        case UpdateStatus.CouldNotDetermine:
                            UIFactory?.ShowCannotDownloadAppcast(this, AppCastUrl);
                            break;
                    }
                });
            }

            return updateData; // in this case, we've already shown UI talking about the new version
        }
```

Given the above is an asynchronous task, the SynchronizationContext used is the default threadpool, rather than the UI context. This means that even though this function is invoked on the UI thread, after the first await the task is free to return to another thread (and indeed in my case does). This means that once we hit the `CheckingForUpdatesWindow?.Close()` call we are no longer on the main thread and an `InvalidOperationException` is thrown due to the cross thread UI access, and the UI is not closed.

**Comment by Deadpikle** [comment]
Should be easy enough to fix by moving the `Close()` call inside the UI  thread portion, I think.

Thanks for the report.

**Comment by brads55** [comment]
Is that sufficient? If `ShowsUIOnMainThread` is set to true then the call to `CallFuncConsideringUIThreads` won't actually dispatch to the UI thread.

**Comment by Deadpikle** [comment]
Yes, you're right, I'm wrong, sorry.

**Comment by Deadpikle** [comment]
Could you post a stacktrace to make sure we're seeing the same error, please?

I found a separate error that I managed to (maybe) fix where the `CheckingForUpdatesWindow` didn't close properly, but it's not in the function you mentioned, although I do see the potential for issues with what you mentioned -- not sure what to do with it quite yet.

Threading issues are never fun. There's got to be a way to make the threading situation easier in this lib without delegating it to the UIs themselves, I would hope...

**Comment by brads55** [comment]
The trace I get is the following:

```
Exception has occurred: CLR/System.InvalidOperationException
Exception thrown: 'System.InvalidOperationException' in System.Windows.Forms.dll: 'Cross-thread operation not valid: Control 'CheckingForUpdatesWindow' accessed from a thread other than the thread it was created on.'
   at System.Windows.Forms.Control.get_Handle()
   at Interop.User32.SendMessageW(IHandle hWnd, WM Msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.Form.Close()
   at NetSparkleUpdater.UI.WinForms.CheckingForUpdatesWindow.NetSparkleUpdater.Interfaces.ICheckingForUpdates.Close() in ...\NetSparkle.UI.WinForms.NetCore\CheckingForUpdatesWindow.cs:line 57
```

It's worth noting that the particular machine I run this on causes different results (perhaps unsurprisingly given threading is involved), I can reproduce this reliably on a lower core count machine, whereas I've never yet hit it on a higher core count machine.

**Comment by brads55** [comment]
I notice now that the above stack trace isn't very helpful since it doesn't go back far enough, instead here is the call stack when that exception arose (on a worker thread).

```
[External Code] (Unknown Source:0)
TmuxTerm.Views.dll!NetSparkleUpdater.UI.WinForms.CheckingForUpdatesWindow.NetSparkleUpdater.Interfaces.ICheckingForUpdates.Close() Line 57 (c...\NetSparkle.UI.WinForms.NetCore\CheckingForUpdatesWindow.cs:57)
TmuxTerm.Views.dll!NetSparkleUpdater.SparkleUpdater.CheckForUpdatesAtUserRequest(bool ignoreSkippedVersions) Line 1563 (...\NetSparkle\SparkleUpdater.cs:1563)
[Resuming Async Method] (Unknown Source:0)
[External Code] (Unknown Source:0)
```

**Comment by Deadpikle** [comment]
Your stack traces were very helpful, thank you.

I think I fixed this in 18915cd. The `CheckingForUpdatesWindow` close operation wasn't doing the check for `InvokeRequired`. Can you please try the latest preview version? (`2.0.7-preview001` for the WinForms .NET Core UI -- should be on NuGet as soon as CI/CD finishes)

**Comment by brads55** [comment]
This appears to have fixed it, thanks! :)

**Comment by Deadpikle** [comment]
The fix is now rolling out as a non-preview version. Thanks again for reporting this and helping me figure it out!
