### ISSUE TITLE
Add .NET 6 targets

### ISSUE THREAD

**Issue by Deadpikle** [NetSparkleUpdater/NetSparkle#252]
.NET 6 is out, so we need to test compatibility and add a .NET 6 target!

(This requires me to update to VS 2022, which might take time...)

**Comment by xaevik** [comment]
Just to let you know, you will run into the following issue of being told that [WebRequest, WebClient, and ServicePoint classes are deprecated](https://docs.microsoft.com/en-us/dotnet/core/compatibility/networking/6.0/webrequest-deprecated).

We ran into this ourselves just last week upgrading a few applications that rely on NetSparkle from .NET 5 to .NET 6 as we have a custom implementation of `IUpdateDownloader` implemented which originally used WebClient. We ended up migrating that implementation to use HttpClient and implementing support for progress reporting. 

For brevity I included an example of such an implementation [here](https://gist.github.com/xaecors/88e30c3810f8c626f6223ee48ce064bf).

**Note**: AsyncHelper.RunAsync implementation is derived from [here](https://github.com/aspnet/AspNetIdentity/blob/main/src/Microsoft.AspNet.Identity.Core/AsyncHelper.cs).

**Comment by Deadpikle** [comment]
@xaecors Thank you for that. That was a huge, HUGE help.

For some reason the Avalonia UI is giving me issues on .NET 6 and the download progress is not triggering properly (somehow the download is finishing before the progress window itself is even created), and I'm not sure yet where that issue lies. But the overall algorithms and things seem to be operating properly.

**Comment by xaevik** [comment]
@Deadpikle 

You're welcome, was happy to help.

That UI issue sounds similar to one I ran into when we implemented a custom UI (to match the look & feel) using that implementation and we're using WPF on .NET 6. I'd be happy to give it a glance if you can refer me to a commit and compare it to see if I can provide a direction.

**Comment by xaevik** [comment]
@Deadpikle 

I've created a gist of our Custom UI implementation (sensitive parts removed), hopefully that will help shed some light your way (assuming it's not an underlying issue with Avalonia).

As a disclaimer the ViewModel leverages the Catel MVVM library so the public properties are are weaved at compile time but use the OnPropertyChanged.Fody behavior under the covers.

https://gist.github.com/xaevik/62f4529e5737b1619c05b8b4bb0e42c4

Edit: updated link and added missing context to gist

**Comment by Deadpikle** [comment]
@xaevik Again, that's super kind of you, thank you.

There was a race condition where the progress window could be shown after the download completed, thus all the events took place before the download window was shown and then of course the download window did nothing UI wise for the user. Fixing that issue seems to have fixed the issues I was experiencing.

You were very helpful for getting this .NET 6 issue completed. Available in the 2.1 preview for now. Thank you so much! 🥳

**Comment by xaevik** [comment]
@Deadpikle 

Happy to be of assistance. That is an interesting race condition though and I saw how you remediated it.

I wonder if it has to do with the AvaloniaUI preferring React observers to events? In any case good to see it's squashed.
