### ISSUE TITLE
Run unit tests in CI/CD

### ISSUE THREAD

**Issue by Deadpikle** [NetSparkleUpdater/NetSparkle#274]
See title. Need to run unit tests in GitHub Actions before doing the deployment.

**Comment by mohitsaxenaknoldus** [comment]
I can do it. Can you please tell me the steps to test this project?

**Comment by Deadpikle** [comment]
Fixed in #270.

> I can do it. Can you please tell me the steps to test this project?

Thank you for your offer, but it was easier for me to just go ahead and do than to explain in this case, sorry. I realize my initial post was not very thorough. All I was looking for was that the test projects (`src/NetSparkle.Tests`, `src/NetSparkle.Tests.AppCastGenerator`) would run their unit tests before the NuGet deployment ran. Unit test projects are pretty standard in C# land and are as easy to execute as running `dotnet test` in the given directory when you're using .NET Core or .NET 5/6+. You can read more about unit tests in C# [here](https://docs.microsoft.com/en-us/visualstudio/test/walkthrough-creating-and-running-unit-tests-for-managed-code?view=vs-2022).

**Comment by Deadpikle** [comment]
Deployed live now that #270 is merged
