### ISSUE TITLE
Version number in UpdateAvailableWindow

### ISSUE THREAD

**Issue by FRvanderVeen** [NetSparkleUpdater/NetSparkle#302]
I've got a question about the version number that is shown in the 'UpdateAvailableWindow'

As far as I could trace it back the AssemblyVersion is used
https://github.com/NetSparkleUpdater/NetSparkle/blob/364e8285c22123192e1c84677ae6873ddb319a42/src/NetSparkle/AssemblyAccessors/AssemblyReflectionAccessor.cs#L132-L138

My assembly also got a FileVersionAttribute. Is it somehow possible to use that version as the 'current version'?

**Comment by Deadpikle** [comment]
Hi @FRvanderVeen! Thanks for your question.

You are right that the `ReflectionAccessor` is used by default, so the version comes from the code that you've pointed out. See the init of the assembly accessor here: https://github.com/NetSparkleUpdater/NetSparkle/blob/5b522b9503438eb700d7cbd5b63637d32d7999e4/src/NetSparkle/SparkleUpdater.cs#L235-L256. The way it gets to the update available window jumps through some hoops, but yes the version ultimately comes from `AssemblyAccessor.AssemblyVersion`. Again, by default being the key phrase.

If you want to get your version or other information from other sources than the defaults, you are free to implement `IAssemblyAccessor` and set the `Configuration` property on your `SparkleUpdater` instance with your chosen `IAssemblyAccessor`, e.g.:

```csharp
var updater = new SparkleUpdater(...)
{
    // adjust the following line for whatever Configuration you need based on OS/your app:
    Configuration = new JSONConfiguration(new MyAssemblyAccessorType(...))
};
```

**Comment by Deadpikle** [comment]
Closing unless there are further questions or bugs. Thanks again for the questions! :)
