### ISSUE TITLE
Event handler leak in WebRequestAppCastDataDownloader.DownloadAndGetAppCastData

### ISSUE THREAD

**Issue by jimpaton-ufx** [NetSparkleUpdater/NetSparkle#303]
The `ValidateRemoteCertificate` event handler that is attached to `ServicePointManager.ServerCertificateValidationCallback` is not unattached before the method returns.

**Comment by Deadpikle** [comment]
Fixed in 6e978c154160bdd7ff62d60af212ed6e61cfd661 (still local to my machine as of this message, but will be pushed sometime today). Thank you for your report!! 😁
