### ISSUE TITLE
Question: How to get version from setup.exe and app.msi ?

### ISSUE THREAD

**Issue by duncangroenewald** [NetSparkleUpdater/NetSparkle#306]
Can I use net sparkle-generate-appcast to get the version from the msi file.  Currently it seems to be find a version in the setup.exe file.

I am using the Visual Studio Project Installer to build the setup.exe and app.msi files.

Thanks

**Comment by Deadpikle** [comment]
Hi @duncangroenewald,

You can rename your files to include the version number. Then, use the `-f true` flag when you use `sparkle-generate-appcast` to have the app cast generator get version information from the file name. For example:

* `Setup 2.3.1.exe`
* `Setup 1.0.4.2.msi`

**Comment by duncangroenewald** [comment]
Hmm, OK so it can't automatically get the version from the application assembly version.  

In any event I seem to have a bigger issue with the updates complaining about having no internet connection or server is not available.  Neither of those are true so there seems to be some other issue.

**Comment by Deadpikle** [comment]
Right now, `FileVersionInfo.GetVersionInfo(filePath)` is used if you want to get the version information from the file. If the `setup.exe` or `setup.msi` file does not have this information in it already, then `FileVersionInfo.GetVersionInfo(filePath)` won't work. 

There are probably other ways to get version information from binaries that this project doesn't do right now (contributions are welcome!), but file versions in the file name work across all platforms.

**Comment by duncangroenewald** [comment]
Thanks, I will see if I can figure it out.  I tried turning on logging but don't see any output.  

You'll have to forgive me I am not usually developing on Windows so the fragility of VS is daunting. One tiny change can bring the house of cards tumbling down and error messages are virtually useless. 

Now even WinSparkle refuses to work anymore complaining of "improperly signed".  There are literally only two commands to run one to generate the keys and the second to sign the setup.exe and after working fine it has suddenly started compiling that the file is improperly signed.

**Comment by Deadpikle** [comment]
It's OK. Take your time. :) You should be able to run this lib on other OS's, although that may or may not be conducive to your overall app. If I/someone need to provide some more help to get you debugging, let me know.

**Comment by Deadpikle** [comment]
How's it going for this issue @duncangroenewald? Got it figured out?

**Comment by duncangroenewald** [comment]
Yes I just rename the msi file thanks.
