### ISSUE TITLE
Error: Sorry either you aren't connected to the internet or our server is having problems

### ISSUE THREAD

**Issue by duncangroenewald** [NetSparkleUpdater/NetSparkle#307]
Any idea why I am getting this error message and how can I debug this.  Turning on the logging option does not appear to write anything to the console when debugging.

**Comment by Deadpikle** [comment]
Hi @duncangroenewald,

This error message generally means that your app cast online is invalid, you forgot to upload the `.signature` file for the appcast, or some other issue with your setup. Or, well, that your internet connection to the server didn't work. 😅 

Turning on the logging option is the best way to go about it and should let you know what is happening. Use Visual Studio's Debug mode and Debug console for this. If all else fails, you can create your own `ILogger` that prints the debug statements to your own file or console output or whatever it is that works best with your application. For instance:

```csharp
var updater = new SparkleUpdater(...)
{
    LogWriter = new MyLogger()
}; 
```

The built-in log writer outputs to `Trace` by default. To make it output to the console, use:

```csharp
var updater = new SparkleUpdater(...)
{
    LogWriter = new LogWriter(true)
}; 
```

Alternatively, you can download this repository's code, redirect one of the sample projects to your app cast URL and signatures, and see what happens by debugging on your own machine!

**Comment by duncangroenewald** [comment]
I have tried turning on debugging but nothing shows up in the console.

**Comment by Deadpikle** [comment]
Please try using your own `ILogger` implementation and use a debugger/breakpoints to see what's going on if you continue to have problems with the built in logging/console within the IDE or other system you're using.

**Comment by duncangroenewald** [comment]
This is what shows up in the debugger

netsparkle: About to start downloading the app cast...
netsparkle: Downloading app cast data...
netsparkle: Downloading app cast signature data...
netsparkle: Signature check of appcast failed
netsparkle: Appcast is not valid
netsparkle: No version information in app cast found

**Comment by duncangroenewald** [comment]
Here is a link https://duncangroenewald.com/files/Software/FocusBracketer/Windows/appcast.xml

**Comment by duncangroenewald** [comment]
Is it possible something about the configuration on the computer used for signing could be getting confused about something when generating the appcast files ?  If so where to start looking ?

**Comment by duncangroenewald** [comment]
Should I try starting over by generating new keys or is that going to make things worse ?

**Comment by Deadpikle** [comment]
>  netsparkle: Signature check of appcast failed

Here is your problem. To verify that this is the problem, you can try forcing the signature checks off by doing:

```csharp
_sparkle = new SparkleUpdater("http://example.com/appcast.xml", new Ed25519Checker(SecurityMode.Unsafe,
                       "base_64_public_key")) // your base 64 public key
{
// ...
};
```

The `SecurityMode.Unsafe` will stop all signature checks. If things work without it, then you know something is going on with your signatures and signing of files.

Things to verify/try:

* Make sure you have uploaded the `.signature` file to your server, which contains the signature for your app cast. It should go to `https://duncangroenewald.com/files/Software/FocusBracketer/Windows/appcast.xml.signature`.
* You can manually create the signature needed by using the app cast generator with the following command: `netsparkle-generate-appcast --generate-signature path/to/app cast.xml`. Then output that to a file with no whitespace.
* Verify that your signature file is valid by: `netsparkle-generate-appcast --verify path/to/app cast.xml --signature base_64_signature`
* Make sure the file permissions to your server files are valid, including both the app cast xml and the `.signature` file

I would try the above and see what happens before generating all new keys.

**Comment by duncangroenewald** [comment]
Yes I checked that the appcast.xml.signature is uploaded, you can check that by just clicking the link to the appcast.xml.signature and the browser will download it.

I also verified the files signatures and that all return valid although I never used the --signature base_64_signature switch so I will try that.

**Comment by duncangroenewald** [comment]
Oh, sorry my bad I did use --signature XXXX. .  I read that as a switch --signature_base_64_signature but just realised that it has a space after signature.  So yep I did use that and it reported everything as verified

**Comment by Deadpikle** [comment]
OK, so since things check out locally, you need to verify that you're setting up NetSparkle itself correctly.

Would you be willing to post your public key here? With that and your app cast URL from a few comments above, I can do some debugging on my end. Your public key is shipped with your software so it's safe to post. (**Don't post your private key**!!)

**Comment by duncangroenewald** [comment]
Sure

EqiBicQndEUOxXkBPIyoGOqXrMAUyNd7wFTqKC4+e7g=

**Comment by Deadpikle** [comment]
Can you please post your initialization code? I am not having any problems with your pub key and app cast URL using the sample project. You should be just fine.

Here is the code I am using:

```csproj
_sparkle = new SparkleUpdater("https://duncangroenewald.com/files/Software/FocusBracketer/Windows/appcast.xml", new Ed25519Checker(Enums.SecurityMode.Strict, "EqiBicQndEUOxXkBPIyoGOqXrMAUyNd7wFTqKC4+e7g="))
{
    UIFactory = new NetSparkleUpdater.UI.Avalonia.UIFactory(Icon), // replace with your UI factory
    ShowsUIOnMainThread = true, // adjust as needed based on WPF/WinForms/etc.
    LogWriter = new LogWriter(true) // shouldn't matter for you here
};
_sparkle.StartLoop(true, true);
```

**Comment by duncangroenewald** [comment]
Hmm, I think I see the problem - I think I was working on the assumption that the default values will use the NetSparkle_Ed2551.pub file to get the public key.

I will pass the key in directly and test with that.

```
// set icon in project properties!
            string manifestModuleName = System.Reflection.Assembly.GetEntryAssembly().ManifestModule.FullyQualifiedName;
            var icon = System.Drawing.Icon.ExtractAssociatedIcon(manifestModuleName);
            _sparkle = new SparkleUpdater(appcast, new DSAChecker(NetSparkleUpdater.Enums.SecurityMode.Strict))
            {
                UIFactory = new NetSparkleUpdater.UI.WPF.UIFactory(NetSparkleUpdater.UI.WPF.IconUtilities.ToImageSource(icon)),
                ShowsUIOnMainThread = false,
                RelaunchAfterUpdate = true,
                //UseNotificationToast = true
            };
```

**Comment by duncangroenewald** [comment]
And using DSAChecker instead of Ed25519Checker ! - duh!  How did I miss that.

**Comment by duncangroenewald** [comment]
Sorted thanks.

**Comment by Deadpikle** [comment]
Glad you got it fixed!

> I think I was working on the assumption that the default values will use the NetSparkle_Ed2551.pub file to get the public key.

`NetSparkle_Ed25519.pub` is the correct file name (I'm guessing that was just a typo there on your part), but yes:

> And using DSAChecker instead of Ed25519Checker

This was the likely cause of the issues. :)

Have fun programming!
