### ISSUE TITLE
NetSparkleUpdater.UI.Avalonia nuget package not working out of the box

### ISSUE THREAD

**Issue by FRvanderVeen** [NetSparkleUpdater/NetSparkle#313]
When I add the NetSparkleUpdater.UI.Avalonia nuget package to my project and it tries to open the UpdateAvailableWindow it throws the following exception:
> System.IO.FileNotFoundException: 'Could not load file or assembly 'Avalonia.HtmlRenderer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.'

The workaround is to install the Avalonia.HtmlRenderer nuget package (https://www.nuget.org/packages/Avalonia.HtmlRenderer/).

I would expect that the nuget package has a dependency to the Avalonia.HtmlRenderer nuget package. On the other hand I see a specific version of the library being included in the lib folder. Another option could be to include that library in your nuget package.

Personally I would go for the first option, to keep things inline with the Avalonia project.

**Comment by Deadpikle** [comment]
Thank you, @FRvanderVeen! The nuget package for `Avalonia.HtmlRenderer` is new as of 6 days ago, so you're right -- no need for a custom-built version now. I've updated the project to use the NuGet reference.

This is rolling out in CI/CD as a preview version now.
