### ISSUE TITLE
netsparkle-generate-appcast CLI does not work with .NET 6

### ISSUE THREAD

**Issue by EllLG1211** [NetSparkleUpdater/NetSparkle#332]
I'm currently writing a WPF app in .NET 6

In its current state, I cannot generate an appcast file through CLI with simply .NET 6. The command will fail if it does not find version 5.0 of Microsoft.NETCore.App in your dotnet\shared files.

Managed to circumvent the issue by installing .NET 5.0 thanks to the link given to me by the CLI.

**Comment by Deadpikle** [comment]
Thanks for reporting this! That's really interesting -- I've definitely set up the project to work with .NET 6:

https://github.com/NetSparkleUpdater/NetSparkle/blob/049525cd0a9aa994ec44fd3463100c95e326ff7e/src/NetSparkle.Tools.AppCastGenerator/NetSparkle.Tools.AppCastGenerator.csproj#L7

But looking on NuGet, it does indeed mark it as .NET 5 only. Might need to upload a new version. Thank you again for reporting!

**Comment by Deadpikle** [comment]
Can you try v2.1? Nuget.org is recognizing this version as compatible with .NET 6.

```
dotnet tool install --global NetSparkleUpdater.Tools.AppCastGenerator --version 2.1.0
```

**Comment by EllLG1211** [comment]
It works now! Thanks for reacting swiftly.
