### ISSUE TITLE
.NET Framework WPF app NetSparkleException.

### ISSUE THREAD

**Issue by CrackAndDie** [NetSparkleUpdater/NetSparkle#336]
I have created app cast files and uploaded them tomy server. Then I paste this into MainWindow constructor:
```c#
var _sparkle = new SparkleUpdater(
    "https://softv.su/SoftHub/Apps/SoftHub/appcast.xml", // link to your app cast file
    new Ed25519Checker(SecurityMode.Strict, // security mode -- use .Unsafe to ignore all signature checking (NOT recommended!!)
                        ConfigurationManager.ConnectionStrings["Ed25519"].ConnectionString) // your base 64 public key -- generate this with the NetSparkleUpdater.Tools.AppCastGenerator .NET CLI tool on any OS
)
{
    UIFactory = new NetSparkleUpdater.UI.WPF.UIFactory(), // or null or choose some other UI factory or build your own!
    RelaunchAfterUpdate = false, // default is false; set to true if you want your app to restart after updating (keep as false if your installer will start your app for you)
    CustomInstallerArguments = "", // set if you want your installer to get some command-line args
};
_sparkle.StartLoop(true);
```
But when I start my app I get the error:
```
Can't read/save configuration data: Error: NetSparkleUpdater is missing the company or productname tag in the assembly accessor (NetSparkleUpdater.AssemblyAccessors.AssemblyReflectionAccessor)
```
What could be the reason of this? Did I miss something?

**Comment by Deadpikle** [comment]
Hi @CrackAndDie,

Thanks for your question. The error means that your `AssemblyInfo.cs` file is missing one or two tags. See the sample for a correct example setup: https://github.com/NetSparkleUpdater/NetSparkle/blob/develop/src/NetSparkle.Samples.NetFramework.WPF/Properties/AssemblyInfo.cs

In other words, add these to your `AssemblyInfo.cs` file:

```csharp
[assembly: AssemblyCompany("My Company")]
[assembly: AssemblyProduct("YourApplication")]
```

Or use your own `IAssemblyAccessor` implementation to supply those values.

**Comment by CrackAndDie** [comment]
Thanks for the answer! I had ```[assembly: AssemblyCompany("")]``` (it was empty). Now it works (I hope so, cause I tested it only once).
