### ISSUE TITLE
SemVer support

### ISSUE THREAD

**Issue by teocomi** [NetSparkleUpdater/NetSparkle#350]
Hi there,

Any plans to support semantic versioning? I tried publishing a `2.0.0-alpha` and got the "could not connect..." issue.

**Comment by Deadpikle** [comment]
Hi @teocomi,

That error is rather vague and we'd have to look at the full log to know what's going on.

That being said, you can support alpha/beta/other channels by using the `AppCastFilter` property on `XMLAppCast` if you like. It's not well documented at this point, and there are a few more details in #291. You can also just use a separate app cast.

As far as actual semantic versioning goes for updates, there are no current plans for that. Pull requests are welcome!

**Comment by teocomi** [comment]
Thanks! I think channels will do for now and I might indeed look at adding semver support if I find the time :)
Feel free to close this in the meantime.

**Comment by Deadpikle** [comment]
Added in #486!
