### ISSUE TITLE
Pass credentials for downloading appcast,installer,...

### ISSUE THREAD

**Issue by meuper** [NetSparkleUpdater/NetSparkle#352]
Hello,
my appcast.xml, installer and so on are hosted on a password restricted nexus repository. Is it possible to pass credentials for that?

**Comment by Deadpikle** [comment]
Hi @meuper,

You can implement your own `IUpdateDownloader` and `IAppCastDataDownloader` for this!

https://github.com/NetSparkleUpdater/NetSparkle/blob/42f21fdc8e8ab1af9ba747788b9e918e5d20d4fb/src/NetSparkle/SparkleUpdater.cs#L421-L430

Easiest thing for you to do is probably to just grab the current implementations and create your own versions based on those.

**Comment by meuper** [comment]
@Deadpikle thank you for the quick reply.
I think it would be easier to customize the http client if there where a method to create it. So we could only override that method to add a header or something. 

As an example, add following method and change [http client creation](https://github.com/NetSparkleUpdater/NetSparkle/blob/42f21fdc8e8ab1af9ba747788b9e918e5d20d4fb/src/NetSparkle/Downloaders/WebRequestAppCastDataDownloader.cs#L83) to 
```cs 
HttpClient httpClient = CreateHttpClient(handler);
```

```cs
protected HttpClient CreateHttpClient()
{
    return CreateHttpClient(null);
}
protected HttpClient CreateHttpClient(HttpClientHandler handler)
{
    HttpClient httpClient;
    // use HttpClient synchronously: https://stackoverflow.com/a/53529122/3938401
    if (handler != null)
    {
        httpClient = new HttpClient(handler);
    }
    else
    {
        httpClient = new HttpClient();
    }
    if (_base64Token != null)
    {
        httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Basic", _base64Token);
    }
    return httpClient;
}
```

**Comment by Deadpikle** [comment]
Hi @meuper,

I have followed your suggestion in `2.1.3-preview20220927001`. There are now `virtual` methods in `WebClientFileDownloader`, `WebRequestAppCastDataDownloader`, and `ReleaseNotesGrabber` that should make this easier for you. Can you let me know if this helps you? :) Thanks!

**Comment by meuper** [comment]
@Deadpikle 2.1.3-preview20220927001 works for me and makes it much easier to use. Thanks :)

**Comment by Deadpikle** [comment]
Rolling out now via CI/CD in version 2.1.3! Thank you again!

**Comment by meuper** [comment]
@Deadpikle It seems the preprocessor conditional removes the CreateHttpClient method from the class WebRequestAppCastDataDownloader

**Comment by Deadpikle** [comment]
@meuper #386
