### ISSUE TITLE
I get a Error when I open the code in VS 2022

### ISSUE THREAD

**Issue by anxofcostas** [NetSparkleUpdater/NetSparkle#379]
Hello! When I try to open the project in my Visual Studio 2022 i get this Error:

Severity Code Description Project Project File Line Status suppressed
Error Could not restore NuGet package for NetSparkle.Xamarin project: 'NuGet.Build.Packaging' package version '0.2.5-dev.8' could not be found.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: The package 'NuGet.Build.Packaging.0.2.5-dev.8' was not found in the source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  https://www.myget.org/F/avalonia-ci/api/v2: 'NuGet.Build.Packaging.0.2.5-dev.8' package was not found in source 'https://www.myget.org/F/avalonia-ci/api/v2'.
  https://api.nuget.org/v3/index.json: Package 'NuGet.Build.Packaging.0.2.5.5-dev.8' was not found in source 'https://api.nuget.org/v3/index.json'.
. See the Error List window for more detailed errors and warnings.

I don´t know how to solve it and I need to modify some things inside of the code.

Thank you.

**Comment by Deadpikle** [comment]
The NetSparkle.Xamarin project is not complete, nor is it functional on Windows. Don't worry about this or try to build it that project. If you're just going to copy the project(s) to your own code, just remove the Xamarin project.

**Comment by anxofcostas** [comment]
Thank you! I'm going to check it.
