### ISSUE TITLE
Add .NET 7 Compatibility

### ISSUE THREAD

**Issue by Deadpikle** [NetSparkleUpdater/NetSparkle#381]
I think .NET 7 is coming out soon (Nov 2022). Hoping that adding .NET 7 compat will be as easy as adding `net7` to all the project files and CI/CD...but we'll see. :)

**Comment by Juanpa93UKG** [comment]
Hello, can I take this?

**Comment by Deadpikle** [comment]
@Juanpa93UKG Contributions are always welcome!

**Comment by Deadpikle** [comment]
Released in v2.2.0
