### ISSUE TITLE
Migrate to BouncyCastle.Cryptography

### ISSUE THREAD

**Issue by jamesweston** [NetSparkleUpdater/NetSparkle#394]
I am using the new version 2.0 of BouncyCastle.Cryptography and it conflicting with the older version Portable.BouncyCastle used in NetSparkle as its using the same namespace. Will NetSparkle be moving to the new package or will you be staying on Portable.BouncyCastle as the new package minimum framework is 4.6.1?

**Comment by Deadpikle** [comment]
Hi @jamesweston,

Thanks for notifying us about this package update! I had no clue there was a new version. Release notes: https://www.bouncycastle.org/csharp/

I can keep the .NET 4.5.2 package on the old dependency and change the others. That's not really a problem at this point, as long as you are not on .NET Framework. Whenever we release a new .NET Framework version bump (#314) we can tweak this.

My question: Would...this be considered a breaking change? Technically this would require a DLL name change of a dependency, but....I think I'm leaning on "no" at the moment....but it might be...

~~This will be available in the next preview version of the software.~~

**Comment by Deadpikle** [comment]
I've changed my mind on making this change immediately since I think it would be a breaking change.

You can get around this issue in your project by following steps outlined here: https://stackoverflow.com/questions/3672920/two-different-dll-with-same-namespace

Thanks again for letting us know about it!

**Comment by jamesweston** [comment]
I will maintain a fork with the changes until 3.x as my project is running on .net 4.8 and extern alias used in the stackoverflow fix is not avalible in vb.net

https://github.com/jamesweston/NetSparkle/commit/0368331baade33864b7803b6cb47a64ff85ec2e2

**Comment by Deadpikle** [comment]
This is now rolling out in 3.x preview 20240716001. (...Yes I typo'd the date.)

**Comment by Deadpikle** [comment]
Please note that preview 20240716002 removes BouncyCastle entirely in lieu of another library for ed25519. Thanks! :-)
