### ISSUE TITLE
Fix `async void` to be `async Task` everywhere

### ISSUE THREAD

**Issue by Deadpikle** [NetSparkleUpdater/NetSparkle#397]
Shouldn't have `async void` anywhere as it hampers others calling the appropriate func and it's not...well, good code.

For future reference: https://learn.microsoft.com/en-us/shows/three-essential-tips-for-async/tip-1-async-void-top-level-event-handlers-only ; https://stackoverflow.com/questions/19415646/should-i-avoid-async-void-event-handlers

**Comment by smty2018** [comment]
@Deadpikle is this issue still open? Can i please give a try at this?

**Comment by Deadpikle** [comment]
> @Deadpikle is this issue still open? Can i please give a try at this?

Yup!

**Comment by smty2018** [comment]
> > @Deadpikle is this issue still open? Can i please give a try at this?
> 
> Yup!

@Deadpikle made a PR for this, can you please review
