### ISSUE TITLE
Can't resolve local download path when generating appcast with -u parameter

### ISSUE THREAD

**Issue by giacarrea** [NetSparkleUpdater/NetSparkle#399]
_Excerpt from my issue posted on gitter:_

I tried to generate an appcast with the download URL's set to "../", then put the appcast in its own directory on my server, but then, while the library did manage to parse the appcast correctly and locate the proper url to download my installer, the library then couldn't resolve the directory to download the file to
Output log:

netsparkle: Starting to download ../Myocene_0.5.1.0-Installer.exe to
netsparkle: IUpdateDownloader: Starting file download from http://localhost/testNetSparkle/Myocene_0.5.1.0-Installer.exe to
Exception thrown: 'System.ArgumentNullException' in System.Private.CoreLib.dll
netsparkle: Error: Path cannot be null. (Parameter 'path')
netsparkle: Download was canceled

I tried to force a value to the tmpdownladfilepath property of my updater object (even tough my regular file works fine), but that didn't change anything

**Comment by Deadpikle** [comment]
Hm, looks like the download file name isn't right. See the first line of the output log.

Have you tried setting `CheckServerFileName` to false just to try that? Might need to debug in the `GetDownloadPathForAppCastItem` function to see why it's returning something blank, as perhaps the code isn't able to grab the filename for some reason. 🤔 

(I haven't the time this moment to sit down and actually debug this myself. Sorry about that. Thank you for logging this on GitHub so we can track the issue.)

**Comment by Deadpikle** [comment]
This is fixed in #620 which will be merged to `develop` in once CI verifies that all still works OK
