### ISSUE TITLE
Missing buttons when HideReleaseNotes is true

### ISSUE THREAD

**Issue by jamesweston** [NetSparkleUpdater/NetSparkle#400]
When setting HideReleaseNotes to true it removes all the buttons from the update available window and makes it impossible to install the update i have a fix in https://github.com/jamesweston/NetSparkle/commit/17b017a4ff448cf07519bfb1b217ccf34a1ece4a if you want me to submit a pull request

Original behaviour
![image](https://user-images.githubusercontent.com/11074434/203302924-f6c69b33-dc65-4d90-8414-2a36801a986a.png)

Fixed behaviour
![image](https://user-images.githubusercontent.com/11074434/203302831-79972418-3ce0-4491-a0ba-1509cc360695.png)

Thanks, James

**Comment by Deadpikle** [comment]
@jamesweston, THANK YOU for reporting this (and the fix)! This was also broken in the .NET Core version and in the Avalonia UI, so thank you for reporting it!

This fix is rolling out in 2.2.1 now via CI/CD. I `cherry-pick`'ed your commit and added you as a co-author on another so you'd get attribution. Thank you!

(And feel free to send in a PR along with filing an issue in the future. No problem there.)
