### ISSUE TITLE
Can you provide compatibility with Avalonia's 11.0.0-preview4 version

### ISSUE THREAD

**Issue by berkansasmaz** [NetSparkleUpdater/NetSparkle#413]
Hi, we are using this library in an application we are developing. Due to some requirements, we had to use version `11.0.0-preview4` of `Avalonia`. However, this time some of our features started to not work. So, we would be very happy if you can provide compatibility with version` 11.0.0-preview4` of `Avalonia`.

**Comment by mightypanda** [comment]
+1 for supporting Avalonia latest previews in cross-platform contexts (Windows, MacOS)
@berkansasmaz what is not working?

**Comment by Rwing** [comment]
I also have this requirement, and I am preparing to do this work. Is there already ongoing work happening to avoid wasting time?

**Comment by Deadpikle** [comment]
Hi all,

I have been out of my home country for several weeks now and recently returned.

PR's are welcome at any time. Right now, I have not put any work into this as Avalonia 11 previews are changing quite a bit between previews, and I was hoping to wait for something more stable. I do not know if I will have time this weekend or not for this. I will see if I can look into it, but I will make no promises for something in the next few days just in case something comes up as I get readjusted to home.

Again, PR's are welcome, and I'm happy to push out preview builds as needed on NuGet once we have something going. (Hooray open source!)

**Comment by Rwing** [comment]
@Deadpikle  I just submitted a PR to solve this problem. Please help me check it. Also, I only tested on Windows and did not test on other OS.

**Comment by Deadpikle** [comment]
All,

3.0.0-preview20230303001 (Avalonia UI package) should be available soon. Credit goes to @Rwing for doing the work (thank you again). Just pushed it via the `avalonia-preview` branch. Seems to work _ok_...the download progress window doesn't start centered on my Mac, and icons aren't showing up. Not sure what's up with both of those issues at this point. Be aware as you use the preview. Thank you.

**Comment by Deadpikle** [comment]
All,

I have just pushed a preview compatible with Avalonia 11 RC 2.2. This one fixes the Icons not showing up, and the centered window thing isn't a problem any more, so I'm calling this issue "good to go" as we now have previews working with Avalonia's latest offerings.

If there are new bugs with future RC's or the final release or similar, please feel free to open another issue. Thanks! :grin:

Edit: The preview compatible with 11 RC 2.2 is `3.0.0-preview20230703001`
