### ISSUE TITLE
NSec.Cryptography dependency

### ISSUE THREAD

**Issue by christophwille** [NetSparkleUpdater/NetSparkle#462]
I might be missing something, but except for the NetSparkle.csproj I seem to not be able to find any usage.

Edit: was the intention to use it for 25519 verification like eg https://gist.github.com/ezekg/e96ef9c71a8f97b9ffcb487b73bfe248 (instead of Bouncy Castle)?

**Comment by Deadpikle** [comment]
You are 100% right. This looks like it is a legacy "oops" that I missed in [#98](https://github.com/NetSparkleUpdater/NetSparkle/pull/98). Will remove.

Thanks for reporting!
