### ISSUE TITLE
Outdated information in README

### ISSUE THREAD

**Issue by christophwille** [NetSparkleUpdater/NetSparkle#475]
![image](https://github.com/NetSparkleUpdater/NetSparkle/assets/344208/9321b14a-8f4e-4dd2-b55d-550315ecca65)

For one, the changelog only exists as old_changelog (404 link as is). Also, is there still value in featuring the renamings prominently?

**Comment by Deadpikle** [comment]
Thanks for pointing that out!

* Removed dead link
* Moved deprecation notes to the FAQ section about searching NuGet
* Various other tweaks
