### ISSUE TITLE
Console.WriteLine logging (remnant I guess)

### ISSUE THREAD

**Issue by christophwille** [NetSparkleUpdater/NetSparkle#477]
https://github.com/NetSparkleUpdater/NetSparkle/blob/a38b203a58c97ff43d43d8dd3ef801590b0048b7/src/NetSparkle/Downloaders/WebRequestAppCastDataDownloader.cs#L135

I don't think having CW here is intentional, more likely a remant of old-style logging.

**Comment by Deadpikle** [comment]
Fixed in #522
