### ISSUE TITLE
Support for Avalonia 11

### ISSUE THREAD

**Issue by BHaesen** [NetSparkleUpdater/NetSparkle#536]
When can we expect support for Avalonia 11?
I'm testing with an Avalonia 11 app to use the AutoUpdater.
When running the app, I get an error message that the assembly Avalonia.Visuals 0.10.21.0 cannot be found.

**Comment by Deadpikle** [comment]
Hi @BHaesen,

We already have support for Avalonia 11 in our preview packages! See #413. Support started in `3.0.0-preview20230703001` and the latest preview runs Avalonia 11.0.5. See https://github.com/NetSparkleUpdater/NetSparkle/blob/18a27c27f5074a5de7321969323c13417af11264/src/NetSparkle.UI.Avalonia/NetSparkle.UI.Avalonia.csproj#L70-L77.

Enjoy!
