### ISSUE TITLE
Is there a way to automatically run the installer after update download?

### ISSUE THREAD

**Issue by RyanG2016** [NetSparkleUpdater/NetSparkle#539]
Once the user checks for updates and chooses to update, the update file downloads and they get prompted to install. Is there a way to have the update automatically run after download?

**Comment by Deadpikle** [comment]
Hi @RyanG2016, there isn't something like a built-in `bool` for this, but you have a few different options:

* You could always auto-download and install via the `UserInteractionMode.DownloadAndInstall` option (`SparkleUpdater.UserInteractionMode`). But that's probably not what you want.
* You could monitor the `SparkleUpdater` events and trigger the download automagically. See the `HandleEventsYourself` sample: https://github.com/NetSparkleUpdater/NetSparkle/tree/develop/src/NetSparkle.Samples.HandleEventsYourself
* But if you did the above you probably want to relabel the button text to "Download and Install" or something. You can modify window contents via the `WindowHandler ProcessWindowAfterInit` on your `UIFactory` OR just implement your own `UIFactory` subclass with the modifications you need.

Does that help? 😄

**Comment by RyanG2016** [comment]
Hi @Deadpikle,
It kind of does. I was thinking it might need a code change. All I really want to do though is auto run after the update is downloaded. So currently, the update notes show and the user chooses whether or not to download. That's fine. I just want to skip the last part after it's downloaded and waits for the user to click Install.
Is that the same thing you're referring to?

**Comment by Deadpikle** [comment]
Yup. So the easiest way to do that is probably to hook into the events to auto install and then to update/modify the UI you can hook into the `UIFactory` `ProcessWindowAfterInit` handler.

**Comment by RyanG2016** [comment]
@Deadpikle We have been able to get this implemented as need per your instruction. Thx
