### ISSUE TITLE
Can not run the update file

### ISSUE THREAD

**Issue by AkiraNoob** [NetSparkleUpdater/NetSparkle#546]
In my case, when install update version of application, the installer download some kind if file i do not understand but not the .exe format, so i can run the update.
![image](https://github.com/NetSparkleUpdater/NetSparkle/assets/89231623/c2f98cc5-f19d-4494-8bb9-16c9d7241150)

**Comment by Deadpikle** [comment]
Hi,

Please set `CheckServerFileName` to `false` on your `NetSparkleUpdater` object when using GitHub releases for downloads as GitHub is using a different internal file name when downloading. I did a quick test and this successfully downloads a file to a `Setup.exe` path.

Thanks for your question! Next time, if possible, please copy paste in your log data as text -- it's much easier to read and copy for testing.

**Comment by AkiraNoob** [comment]
Thank you very much @Deadpikle , you save my day. Really sorry for my mistake make this hard to read and copy, I will remember next time. Have a nice day.

**Comment by Deadpikle** [comment]
No worries. Glad it works! :-)
