### ISSUE TITLE
SemVer compare versions

### ISSUE THREAD

**Issue by DanieleVar** [NetSparkleUpdater/NetSparkle#573]
Hi, 
I'm using the preview version 3.0.0-preview20240120001 of .NET Sparkler Updater UI WPF.
I've got a trouble when I use the semver version of my file because the updater discard the new versions. I think because the compare of versions is made on "version file" instead of "version" property.

How you can see in the screenshot I've got a 1.11.0-beta.3 version of my software and the appcast.xml contains the newer 1.11.0-beta.4.
The log writes that 1.11.0-beta.4 is older than 1.11.0 and is true.. but the current version is 1.11.0-beta.3.
![image](https://github.com/NetSparkleUpdater/NetSparkle/assets/11925650/9862f83d-4612-45ac-bc39-52463a37c8d7)

I've tried to force the version file property to 1.11.0-beta.4 but dotnet don't like it:

![image](https://github.com/NetSparkleUpdater/NetSparkle/assets/11925650/0ad0015c-c51e-4ab8-a77d-e920572a2007)
![image](https://github.com/NetSparkleUpdater/NetSparkle/assets/11925650/4c12b200-db56-42a0-930c-7c52d6438459)

Do you think that is that use "version" property instead of "version file" could be the right way to resolve this issue?

**Comment by Deadpikle** [comment]
Hi,

Thanks for your report. I'm a little confused: The beta version is older, so NetSparkleUpdater is taking the right action by offering `1.11.0` (newer software) rather than `1.11.0-beta4` (older version technically). Are you wanting to let the user upgrade to any version, even if it's not the latest version...?

**Comment by DanieleVar** [comment]
Hi,
I'm sorry but I explained myself badly.
What I would like to say is that I created version 1.11.0-beta.3 but from my pipeline the file version is 1.11.0 because dotnet does not accept characters other than numbers. When I did version 1.11.0-beta.4 NetSparkle compares the version of the file with that of the appCast and, as you say, finds that 1.11.0 is new compared to 1.11.0-beta.4.

I tried to modify the code so that it doesn't consider the "version file" property but "version" and everything works.
But I don't know if this change will impact other logics in any way. For now I'll test it in my enviroment and if it seems to me that everything is working well I'll let you know.

**Comment by Deadpikle** [comment]
Hi,

You can create your own `IAssemblyAccessor` and use that for the `Configuration` that you are using. The `IAssemblyAccessor` would be able to set your version number for your app as whatever you want it to be (and read it from wherever you want to read it from). That wouldn't require any changes to the `NetSparkleUpdater` code itself and should do what you want. :-)

**Comment by Deadpikle** [comment]
Oh, and don't worry about explaining well or not well. Don't worry about that at all. We're all here to help one another, and I appreciate you coming back and clarifying what was happening. :-)

**Comment by DanieleVar** [comment]
Hi, 
I've implemented the `IAssemblyAccessor` interface on my class and used for the `Configuration` and seems to work!
I will do some tests and I'll return to you if something not work.
Thanks!
