### ISSUE TITLE
Problem inheriting from WebClientFileDownloader class and overriding CreateHttpClient method

### ISSUE THREAD

**Issue by bdovaz** [NetSparkleUpdater/NetSparkle#575]
In the 2 constructors of this class a virtual method is invoked (PrepareToDownloadFile > CreateHttpClient)  and this is not good practice and is causing me problems:

https://github.com/NetSparkleUpdater/NetSparkle/blob/225fb7be3fee10c262d6c8e3f312fc9cd71bba69/src/NetSparkle/Downloaders/WebClientFileDownloader.cs#L36

In sonar you can see why it should not be done and that it is just my exact problem:

https://rules.sonarsource.com/csharp/RSPEC-1699/?search=virtual

**Comment by Deadpikle** [comment]
Thanks for the heads up! Fixed in 420f961dfa9c9071332e2e0737b0f287d2cfa5dc and preview version rolling out now.
