### ISSUE TITLE
Support Nullable reference types

### ISSUE THREAD

**Issue by bdovaz** [NetSparkleUpdater/NetSparkle#577]
https://learn.microsoft.com/en-us/dotnet/csharp/nullable-references

**Comment by Deadpikle** [comment]
This is being worked on in #595 and progress is being tracked there; contributions to help with those efforts are welcome. Thank you for the recommendation to add this; this will be great to have in the library.

**Comment by Deadpikle** [comment]
Done, but a note: The PR explicitly added nullability WITHOUT considering some refactoring that needs to be done. That will come later in other PRs/work, so some of the nullability additions here may be tweaked later as refactoring happens. (Some nullability changes were especially ugly/I didn't like, but they were in areas I was considering for refactoring later.)

In any case, nullability is now a feature that will be considered moving forward, and it's enabled on all applicable projects, so this is a good step forward. :-)
