### ISSUE TITLE
Update works but file does not save to disk

### ISSUE THREAD

**Issue by archipoeta** [NetSparkleUpdater/NetSparkle#610]
Hi,
Thanks your great work with NetSparkleUpdater! 🥳

So, the best way I can describe the issue is that--
Everything works, updates are downloaded and the exe relaunches the updated application, but appears to not actually save the file to disk. Basically the version running in memory is verifiably updated (1.0.2) while the file on disk remains (1.0.1).

This is only my second update of my application with NetSparkleUpdater so admittedly am likely doing something wrong.
Any thoughts or advice is appreciated. 🙏

**Comment by archipoeta** [comment]
Using `2.3.0`

**Comment by Deadpikle** [comment]
Hi!

This means your update isn't being installed or placed where your installed version is. For example, this can happen if your running version is portable and running from, say, your desktop, but the installer you download installs to C:/Program Files (or similar). 

What kind of update file/installer are you using? Is your installed version portable? What kind of installer are you using?

**Comment by archipoeta** [comment]
That tracks with what I'm seeing, it's supposed to be downloading an updated version of the enclosing/executing application exe*, replacing itself in whatever current directory it happens to be placed in. 🤔Not using an installer due to the relatively simple use case. I swear this worked once in the past, or I'm crazy-- or both. 😛

**Comment by Deadpikle** [comment]
Well, I can't tell you if you're crazy or not...🤪

Generally this lib runs whatever is downloaded and doesn't move it anywhere. On Mac you can distribute in a zip to overwrite your current app but that isn't available on windows. So if you are downloading your raw program, it's just going to assume that's the installer and run it. So your exe is somewhere in your temp folders. 

You very likely can't replace your exe while it's running either. I'm guessing?

So, my thought is that you need to use a custom SparkleUodater instance and override the method that generates the batch file that runs after your software closes and make it do the file replacement, using the path to your running executable somewhere in there. ...which makes me wonder what your RestartExecutable____ sparkle instance members are evaluating to. You may want to check those too.

**Comment by Deadpikle** [comment]
The function you're gonna want to look at is SparkleUpdater.RunDownloadedInstaller. (Sorry on my phone atm or I'd link it directly.) the develop branch has had major changes since 2.3 but that one hasn't changed much if at all for windows, I believe, so should still be ok to look over.

**Comment by archipoeta** [comment]
Oh ok, yeah, I'm crazy. 🤪
I think we're at the "how did it ever work" stage-- thank you for the sanity check, I did find it in Temp. 🙏👍🥳

**Comment by Deadpikle** [comment]
If you come up with a solution that involves replacing your exe with a downloaded, non-installer exe, and you're able, please post your solution and/or details on it so others can know how to do it, too. :-) Thanks!

**Comment by archipoeta** [comment]
Ok so I basically used the example from: https://github.com/NetSparkleUpdater/NetSparkle/blob/6190ecbdfa0d8c1cdcbed18e0f3a1049323d1873/src/NetSparkle.Samples.Avalonia.MacOS/CustomSparkleUpdater.cs#L57

And the only edit made was to the outputted batch file as per your suggestion. 🙏 
```batch
                            :install
                            copy /b /y {downloadFilePath} ""{workingDir}""
                            :afterinstall
                            {relaunchAfterUpdate.Trim()}
```
Appreciate the help! ❤️

**Comment by Deadpikle** [comment]
Great!! I'd probably wrap `downloadFilePath` in quotes too （`""{downloadFilePath}""`) juuuuust in case someone has a space somewhere in the path, but that should work. Assuming it's not anywhere that requires admin permissions, I'd guess, but yeah, that seems like the right way to go. If you do need admin permissions, [this SO post](https://stackoverflow.com/questions/2532769/how-to-start-a-process-as-administrator-mode-in-c-sharp) probably will help (and you'd modify the `_installerProcess` variable use in the same function).

Glad it works!! :-) Thanks for responding with the solution.

OK to close the issue since it seems to be resolved?

**Comment by archipoeta** [comment]
💯 Appreciate you!
