### ISSUE TITLE
Switch to using PackageLicenseExpression

### ISSUE THREAD

**Issue by bdovaz** [NetSparkleUpdater/NetSparkle#615]
License expression is the preferred way (shows in NuGet.org and used in license validations)

https://learn.microsoft.com/en-us/nuget/create-packages/package-authoring-best-practices#licensing

Example:

```xml
<PropertyGroup>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
</PropertyGroup>
```

**Comment by Deadpikle** [comment]
Thank you for the recommendation! :-) This is now done in all packages and will of course roll out whenever the next preview is released.
