### ISSUE TITLE
Avalonia download window does not follow theme

### ISSUE THREAD

**Issue by Deadpikle** [NetSparkleUpdater/NetSparkle#619]
In the UI refactoring, we updated the background color of the download window so we could set the color to `Tomato` if the signature check failed (this never happened and only happened on WinForms). However, setting the background color to `Transparent` makes the window not follow Avalonia's current window theme. We should only set the background color if absolutely necessary on Avalonia.

**Comment by Andreysht** [comment]
Hi @Deadpikle!

Looks like this [if(true)](https://github.com/NetSparkleUpdater/NetSparkle/commit/4ce7df452f8ae3a48ab90283dcc1b24de801d09d#diff-e4627baf9a383062d83692df43042e7dde90e3a2d3a39c9785f596ca7aa3badeR162) needs to be removed.

**Comment by Deadpikle** [comment]
@Andreysht Thank you so much for catching that. This is what happens when you forget to remove your debug code, lol. 

There's a new preview running its way through CI/CD now for the Avalonia UI that'll fix this. Sorry about that!
