### ISSUE TITLE
Add EdDSA/ed25519 ISignatureVerifier

### ISSUE THREAD

**Issue by Deadpikle** [NetSparkleUpdater/NetSparkle#62]
See https://github.com/vslavik/winsparkle/issues/187 and changes in [Sparkle](https://github.com/sparkle-project/Sparkle). Would need to create a new class that implements `ISignatureVerifier`.

**Comment by Deadpikle** [comment]
There's an ed25519 library compliant with .NET Standard here: https://github.com/Deadpikle/Chaos.NaCl (forked from https://github.com/CodesInChaos/Chaos.NaCl). It's in the public domain. If that were to be referenced from our project, implementation would be fairly straight forward.

**Comment by Bren2010** [comment]
@Deadpikle If this is easy, do you mind doing it? DSA-SHA1 signatures haven't been secure [for many years](https://www.computerworld.com/article/3173616/the-sha1-hash-function-is-now-completely-unsafe.html), and it would be nice to have a secure option

**Comment by Deadpikle** [comment]
@Bren2010 I will try to do it within the next week if I can!

**Comment by mphill** [comment]
Just wanted to chime in, I added Ed25519 support the to AppCastGenerator last night.

DSACryptoServiceProvider is a thin windows only wrapper. Can't generate keys on linux / mac.

I can implement ISignatureVerifier for Ed25519 this weekend, we can switch the project over to Ed25519 if you want.

Let me know.

**Comment by Deadpikle** [comment]
I was planning to work on it this Sunday if I could. I don't mind if you open a PR for it, but there's no rush. I'll check again Sunday whenever-I-get-to-it to see if you've done it already; if not, I'll work on it. (Also planning to look at your other PR on Sunday.)

I am planning/will want unit tests for Ed25519 stuff. We'll also need a new/updated command line tool for verifying/checking/generating Ed25519 keys.

I really appreciate your help, here.

**Comment by mphill** [comment]
https://github.com/mphill/NetSparkle

I didn't do a PR yet, but I already merged the command line checker into the app cast app and created Ed25519Checker. 

These are the new options:

```
 --generate-keys                   Generate keys

  --force                           Force regeneration of keys

  --generate-signature              Generate signature from binary

  --verify                          Binary to verify
```

**Comment by Deadpikle** [comment]
@Bren2010 Ed25519 support is now on `develop` and is in `v2.0.0-preview20200607001` (available once CD finishes) along with many updates to the app cast generator tool! Please test it out and let us know if you have any issues.

**Comment by Bren2010** [comment]
Thank you!!
