### ISSUE TITLE
Broken Version Number Detection in AppCastGenerator (with file names having multiple dashes)

### ISSUE THREAD

**Issue by eminsenay** [NetSparkleUpdater/NetSparkle#623]
A few months ago #588 was opened and fixed for AppCastGenerator version number detection. There, the file name which was given as an input to AppCastGenerator was containing a dash "-" character.

Today, I realized that the fix only works for files having a single dash character. For file names having multiple dashes, the problem still persists.

Example with a file name `setup-something-1.3.0.dmg`:

```
netsparkle-generate-appcast --key-path .\Setup\netsparkle\ -a .\Setup\ -b .\Setup\ -u <something> -p ./ReleaseNotes/MacOS/ -n "appname" -f true --os mac --ext dmg
```

resulting in 

```
Operating System: mac
Searching: .\Setup\
Found 1 *.dmg files(s)

Found a binary with version 3.0
Writing xml app cast to .\Setup\appcast.xml
Wrote .\Setup\appcast.xml.signature
```

The version number is incorrectly detected as 3.0. 1.3.0 is expected.

As this was the case in #588, as a workaround, I switched back to v2.5.2 as it works for this file as intended.

Note: "Found 1 *.dmg files(s)" text also need a minor correction as "Found 1 *.dmg file(s)".

**Comment by Deadpikle** [comment]
@eminsenay Thanks for filing the bug and being thorough in your report!

2.8.2 of the app cast generator is rolling its way through CI/CD now and that will fix this bug for ya.

Thanks!
