### ISSUE TITLE
Path is sometimes null when downloading from Unity Cloud

### ISSUE THREAD

**Issue by MagikBased** [NetSparkleUpdater/NetSparkle#627]
I've been trying to follow the HandleEventsYourself example but there's about a 50/50 chance it works incorrectly. This mainly seems to stem from me using Unity Cloud as my storage for my installer. Unity Cloud uses a link which doesnt contain the .exe path inside of it. Here is the output I'm getting when it fails to populate path:

> 17:58:29:968	netsparkle: Preparing to download https://aebdd224-205e-40e7-9da3-75f2b3226c02.client-api.unity3dusercontent.com/client_api/v1/environments/5c19291c-afe2-46d5-bcc7-7653850d8040/buckets/57439eb8-eedc-43b3-81c8-39ad20a35ace/entries/7937e0a4-e2cb-4d8f-ad02-e05f4619ed57/versions/f9cc4a10-ca85-4bff-9884-59ed28756c35/content/
> 17:58:29:968	netsparkle: IUpdateDownloader: Preparing to download file...
> 17:58:29:968	netsparkle: IUpdateDownloader: Creating new HttpClient...
> 17:58:29:968	'XalterverseLauncher.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Net.NetworkInformation.dll'. 
> 17:58:29:968	User Chose to Install
> 17:58:29:968	netsparkle: Starting to download https://aebdd224-205e-40e7-9da3-75f2b3226c02.client-api.unity3dusercontent.com/client_api/v1/environments/5c19291c-afe2-46d5-bcc7-7653850d8040/buckets/57439eb8-eedc-43b3-81c8-39ad20a35ace/entries/7937e0a4-e2cb-4d8f-ad02-e05f4619ed57/versions/f9cc4a10-ca85-4bff-9884-59ed28756c35/content/ to 
> 17:58:29:968	netsparkle: IUpdateDownloader: Starting file download from https://aebdd224-205e-40e7-9da3-75f2b3226c02.client-api.unity3dusercontent.com/client_api/v1/environments/5c19291c-afe2-46d5-bcc7-7653850d8040/buckets/57439eb8-eedc-43b3-81c8-39ad20a35ace/entries/7937e0a4-e2cb-4d8f-ad02-e05f4619ed57/versions/f9cc4a10-ca85-4bff-9884-59ed28756c35/content/ to 
> 17:58:29:968	The thread '[Thread Destroyed]' (26672) has exited with code 0 (0x0).
> 17:58:30:460	Exception thrown: 'System.ArgumentNullException' in System.Private.CoreLib.dll
> 17:58:30:460	netsparkle: Error: Value cannot be null. (Parameter 'path')
> 17:58:30:460	netsparkle: Error on download finished: Value cannot be null. (Parameter 'path')
> 17:58:30:460	OnDownloadError Path: 
> 17:58:30:460	Error Download path: C:\Users\jenha\AppData\Local\XalterverseLauncher\updates
> 17:58:30:460	Error downloading XalterverseLauncher: Value cannot be null. (Parameter 'path')
> 17:58:34:562	The program '[1412] XalterverseLauncher.exe' has exited with code 0 (0x0).

Here is the output I get when it does correctly populate path:

> 18:05:30:665	netsparkle: Preparing to download https://aebdd224-205e-40e7-9da3-75f2b3226c02.client-api.unity3dusercontent.com/client_api/v1/environments/5c19291c-afe2-46d5-bcc7-7653850d8040/buckets/57439eb8-eedc-43b3-81c8-39ad20a35ace/entries/7937e0a4-e2cb-4d8f-ad02-e05f4619ed57/versions/f9cc4a10-ca85-4bff-9884-59ed28756c35/content/
> 18:05:30:665	netsparkle: IUpdateDownloader: Preparing to download file...
> 18:05:30:665	netsparkle: IUpdateDownloader: Creating new HttpClient...
> 18:05:30:915	'XalterverseLauncher.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Net.NetworkInformation.dll'. 
> 18:05:31:416	netsparkle: File is already downloaded
> 18:05:31:416	User Chose to Install
> 18:05:31:416	The thread '[Thread Destroyed]' (9040) has exited with code 0 (0x0).
> 18:05:31:416	OnDownloadFinished Path: C:\Users\jenha\AppData\Local\XalterverseLauncher\updates\f9cc4a10-ca85-4bff-9884-59ed28756c35
> 18:05:31:416	Renamed downlaoded file to: C:\Users\jenha\AppData\Local\XalterverseLauncher\updates\f9cc4a10-ca85-4bff-9884-59ed28756c35.exe
> 18:05:31:416	Download path: C:\Users\jenha\AppData\Local\XalterverseLauncher\updates\f9cc4a10-ca85-4bff-9884-59ed28756c35.exe
> 18:05:31:416	Install update path: C:\Users\jenha\AppData\Local\XalterverseLauncher\updates\f9cc4a10-ca85-4bff-9884-59ed28756c35.exe
> 18:05:31:416	_sparkle: NetSparkleUpdater.SparkleUpdater
> 18:05:31:416	item: NetSparkleUpdater.AppCastItem
> 18:05:31:416	netsparkle: IUpdateDownloader: Preparing to download file...
> 18:05:31:416	netsparkle: IUpdateDownloader: HttpClient existed already. Canceling...
> 18:05:31:416	netsparkle: IUpdateDownloader: Creating new HttpClient...
> 18:05:31:665	'XalterverseLauncher.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Diagnostics.Process.dll'. 
> 18:05:31:665	netsparkle: Running downloaded installer
> 18:05:31:665	netsparkle: Generating batch in C:\Users\jenha\AppData\Local\Temp\9bf01b28-f638-4280-8fca-643f6ff27ea2.cmd
> 18:05:31:665	netsparkle: Going to execute script at path: C:\Users\jenha\AppData\Local\Temp\9bf01b28-f638-4280-8fca-643f6ff27ea2.cmd
> 18:05:31:665	netsparkle: Starting the installer process at C:\Users\jenha\AppData\Local\Temp\9bf01b28-f638-4280-8fca-643f6ff27ea2.cmd
> 18:05:31:665	netsparkle: Shutting down application via CloseApplication...
> 18:05:33:731	The program '[25696] XalterverseLauncher.exe' has exited with code 0 (0x0).

I did have to manually append ".exe" to path if it doesn't end with it as netsparkle would only create a file with no extension type and prevent the installer from running. 
I did see from previous isses setting CheckServerFileName to false would help in this regard however that didn't work for me and would cause path to always be null.
I attempted to manually set TmpDownloadFilePath as well but this did not seem to have any effect.

**Comment by Deadpikle** [comment]
Hi @MagikBased,

Thanks for the report and looking for solutions already. This is an odd one, but I'm not sure the logs from the second one indicate success, as the logs say, `18:05:31:416 netsparkle: File is already downloaded`.

Can you confirm:

1) What version of the library you are using (if 2.3, can you try the latest preview?)
2) That your `SparkleUpdater` object is being created on the main thread/that you are doing other operations on the main thread of your application?

Thanks!

Edits:

`TmpDownloadFilePath` is for using along with the filename that is found online. Right now, there is no filename found online at all, so...I'm not sure why this ever works at all at the moment...

**Comment by Deadpikle** [comment]
So, the server returns a file without an executable extension.

1. `WebFileDownloader.RetrieveDestinationFileNameAsyncForUri` fails as it just checks the headers for the download and not the full contents. This is apparently not enough for Unity Cloud to get the download file name.
2. If you swap to `ResponseContentRead`, it will grab the download file name, but without an extension, as you've noted.
3. NetSparkle needs an extension as you've noted, but right now the `GetDownloadPathForAppCastItem` doesn't let you control this.

Remedies implemented/options available:

1. Made `SparkleUpdater.GetDownloadPathForAppCastItem` virtual for easier overriding of behavior.
2. Made `WebFileDownloader.RetrieveDestinationFileNameAsync`virtual for easier overriding of behavior
3. Added `SparkleUpdater.TmpDownloadFileNameWithExtension` to control the download file name with extension

You should be able to pick any of those options and get the behavior you need for your situation to make it more consistent, with #3 being the easiest option (set it to something like MyAppVersionV1.3.exe or something based off the `AppCastItem` -- just make sure it's **consistent** based on `AppCastItem`).

Available in `3.0.0-preview20241016001`.

Let me know if that helps.

In your testing, make sure you delete the tmp downloaded item as needed so it downloads fresh each time. It'll sit in your tmp dir (or other download location) otherwise.

**Comment by MagikBased** [comment]
Thanks for the quick response. I was on 2.3 and I believe the sparkle object was on the main thread. I updated to the preview and implemented the TmpDownloadFileNameWithExtension and that seems to have resolved the issue. Thanks for your help, I'll look into deleting the tmp files after its done now.
