### ISSUE TITLE
[Input Wanted] Organization Name

### ISSUE THREAD

**Issue by Deadpikle** [NetSparkleUpdater/NetSparkle#73]
Hi anyone who reads this!

In working on a 2.0 version of NetSparkle, this library really needs to be moved off of my fork to a GitHub organization for easier discoverability and searching.

Unfortunately, the name "NetSparkle" ([github.com/NetSparkle](https://github.com/NetSparkle)) is already taken. I am looking for ideas on what to call the GitHub organization.

Should we rename NetSparkle entirely? (I don't know if this is a good idea.) Add a prefix/suffix? I want to keep spaces and punctuation out _if_ we can so that URL stuff is easy.

Ideas:

* NewNetSparkle
* NetSparkle.New
* ~~NetSparkle-vNext~~
* NetSparkle Reborn
* NetSparkleShine
* ???

Any input appreciated. I'd like to stick close to the original NetSparkle name so we can keep the NetSparkle NuGet repo and not make it look like NetSparkle (which has Google results, etc.) is dead.

**Comment by schtritoff** [comment]
More proposals:

NetSparkleNG/NetSparkleNG
NetSparkleOrg/NetSparkle

**Comment by Mostlypyjamas** [comment]
I was going to suggest NetSparkle.NET but then realised that would be somewhat redundant!  

Whilst I like the sound of a -vNext, I wonder if that makes it feel like it will be what to use "next" but not right now as that sort of is how Microsoft use it - fine for now, but not if you are stuck with it in a years time and it's long become the main "active" version.

**Comment by Deadpikle** [comment]
Thanks for your input! Good point about `vNext`, there. Forget that one.

What about NetSparkleUpdater/NetSparkle? It keeps the original name while adding clarity of purpose to newcomers who aren't familiar with the Sparkle project in general.

**Comment by Mostlypyjamas** [comment]
Netsparkleupdater sounds like a really option- we actually hadn't heard of sparkle feeds until Microsoft added them to app enter, but we had searched nuget for automatic update packages plenty of times, and I suspect overlooked anything sparkly as we just didnt know what it was!

Putting updater on the end makes a lot of sense

**Comment by Deadpikle** [comment]
This is what I'll go with unless I get complaints:

Name => `NetSparkleUpdater`. We keep the base name but add `Updater` to help people know what this is used for. I thought about `NetSparkleAppUpdater` but it's really close to [NAppUpdate](https://github.com/synhershko/NAppUpdate).

* GitHub org: `NetSparkleUpdater/NetSparkle`
* NuGet Packages
  * `NetSparkle` (eventually deprecate but it has traction and a lot of downloads so might start publishing previews...maybe...not sure yet) -- [NuGet](https://www.nuget.org/packages/NetSparkle/)
  * `NetSparkleUpdater` -- the new home of `NetSparkle` on NuGet
  * `NetSparkleUpdater.UI.WPF` -- need to make this compatible with `dotnetcore3.0` and multi-target before creating this NuGet feed
  * `NetSparkleUpdater.UI.WinForms` -- need to make this compatible with `dotnetcore3.0` and multi-target before creating this NuGet feed
  * `NetSparkleUpdater.UI.Avalonia` (eventually; probably Windows only).
  * `NetSparkle.New` may keep getting preview packages and the initial 2.0 package, but won't get the new UI stuff. **There is already a preview package published here of the `netstandard2.0` version as of 2020-02-14, but no prebuilt UI stuff on NuGet yet.**

I will deprecate `NetSparkle.New` when 2.0 is released....or maybe sooner and point people to `NetSparkleUpdater`.

**Comment by Mostlypyjamas** [comment]
This sounds like a really good roadmap - and I think NetSparkleUpdater sounds like a really good new name - clean and like you say, really explains what it does clearly

**Comment by Deadpikle** [comment]
This repo is now setup as a normal repo (not a fork of a repo) so that it can be more easily searched -- found out that when you transfer a repo, it still acts like it is a fork. 

**This repo will be moving to `NetSparkleUpdater` ([GitHub here](https://github.com/NetSparkleUpdater)) sometime soon!!**

**Comment by Deadpikle** [comment]
We are now at https://github.com/NetSparkleUpdater/NetSparkle!
