### ISSUE TITLE
Documentation Updates

### ISSUE THREAD

**Issue by Deadpikle** [NetSparkleUpdater/NetSparkle#89]
* [x] Document that if you don't implement a UIFactory, you must handle `CloseApplication` or `CloseApplicationAsync` yourself!!!
* [x] ~~Update README.md with all the new / changed public APIs~~ (update: decided to rely on XML docs for method details and params instead of plopping all docs here on the repo. Maybe in the future we can use some automation to put those on the NetSparkleUpdater website or something, I guess.)
* [x] Go through the entire code base and document all functions (or update docs as needed) in the core NetSparkle (2020-04-26 update: partially done. building gives no warnings for core NetSparkle, but need to update docs in some places)
* [x] Go through and make it so that building gives no documentation warnings (read: add docs for UI projects)
* [x] Add more examples of valid app cast generator syntax to both the console app and README
* [x] ~~Add some more samples in these docs for doing things~~ (update: there are already sample apps and docs for this purpose)
* [x] Add docs on choosing your UI and which package you should install for your needs
* [x] ~~Separate docs into multiple files for a less humongous README~~ (update: decided to rely on XML docs for method details and params instead of plopping all docs here on the repo. Maybe in the future we can use some automation to put those on the NetSparkleUpdater website or something, I guess.)
* [x] Items from #96 
* [x] Add FAQ

**Comment by flemingm** [comment]
Localization information from the old site seem to be missing, also may need updated due to changes. I can only find APP variable being handled (I search all file for both text and TEXT.Replace). The DOWNLOAD and OLDVERSION variable do not seem to be used in current version.

ie.  
<value>APP が利用可能になりました。 （OLDVERSION があります） 今すぐ [DOWNLOAD] しますか？</value> 

UpdateAvailableWindow.JA.resx:131:

**Comment by Deadpikle** [comment]
Yes, there is a serious lack of localization capabilities right now in the 2.0 beta. Only the WinForms app "sort of" did localization in the first place, and the Avalonia/WPF UIs don't have any localization support, basically.

I will make a new issue for localization support for a 2.x version.

**Comment by Deadpikle** [comment]
Wooo, doc updates are basically done!
