### ISSUE TITLE
Download finished message displayed on non UI thread after Download

### ISSUE THREAD

**Issue by owaits** [NetSparkleUpdater/NetSparkle#94]
If I run the WinForms sample and when prompted the update select update it starts to download the version to install but once the download is finished the update occurs on a non UI thread causing a cross thread exception. 

The function FinishedDownloadingFile is called in NetSparkleUpdater.UI.WinForms.DownloadProgressWindow it then tries to set the progressDownload visibility but it is not on a UI thread and so you get a cross thread exception.

**Comment by Deadpikle** [comment]
Hey @owaits, I appreciate your bug reports! This has been fixed and is in the new preview version `2.0.0-preview20200512001`. Thank you!
