### ISSUE TITLE
Error text does not fit for WinForms

### ISSUE THREAD

**Issue by owaits** [NetSparkleUpdater/NetSparkle#95]
If an error occurs with the connection, the resulting error message does not fit in the dialog and is truncated quite abruptly.

![image](https://user-images.githubusercontent.com/13810266/81743069-f71c7a80-9498-11ea-9a3a-3b1063ab1075.png)

To re-produce this simply set the appcast url to nonsense in the NetSparkleUpdater.Samples.NetFramework.WinForms sample and select Explicit User Request To Check.

**Comment by Deadpikle** [comment]
Hey @owaits, thanks for reporting this! This has been fixed and the fix is in the new preview version `2.0.0-preview20200512001`. Thank you!
