### ISSUE TITLE
NetSparkle.Tests is .NET Framework

### ISSUE THREAD

**Issue by mphill** [NetSparkleUpdater/NetSparkle#99]
I can't add unit tests as a developer because .NET Framework projects won't open on Macs.

I think that .net core or standard should be the targets for all project unless absolutely necessary.

There are some good techniques for supporting multiple targets in the same project

https://github.com/jamesmontemagno/VibratePlugin/blob/master/src/Vibrate.Plugin/Vibrate.Plugin.csproj is a project for Xamarin that conditionally includes files based on the target, they all share the same shared Interfaces.  This could help with some of `TargetFrameworkVersion v4.5.2` targeting.

As an option for unit testing that could work well for all platforms I would recommend NUnit - it has a great track record and adoption.

**Comment by Deadpikle** [comment]
Thanks for the report!

I've made the unit test project compatible with both .NET Framework and .NET Core. I prefer XUnit to NUnit, so I also converted the project to use XUnit.

I also bumped the minimum .NET Framework version to 4.5.2 from 4.5.1. We are not dropping support for .NET Framework at this time. Based on the download stats, we have plenty of people still using .NET Framework (for WinForms at least). Perhaps an eventual 3.0 could drop .NET Framework support -- right now, I see no good reason to drop .NET Framework support.
